"""EntityProfile Types and Enums."""
# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code

# Autogenerated
# DO NOT MODIFY

from typing import Optional, List, Dict, Union, Any, Tuple


from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, config


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class EntityProfileDataPoint:
    """EntityProfileDataPoint."""

    timestamp: Optional[str] = field(
        default=None, metadata=config(field_name="Timestamp")
    )
    feature_count: Optional[int] = field(
        default=None, metadata=config(field_name="FeatureCount")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class AuthAttemptsTimeline:
    """AuthAttemptsTimeline."""

    source_ip_data_points: Optional[List[EntityProfileDataPoint]] = field(
        default=None, metadata=config(field_name="sourceIPDataPoints")
    )
    target_username_data_points: Optional[List[EntityProfileDataPoint]] = field(
        default=None, metadata=config(field_name="targetUsernameDataPoints")
    )
