"""ContextSummarizer Mutation."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING


if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.context_summarizer import ContextSummarizerService

log = logging.getLogger(__name__)


class TaegisSDKContextSummarizerMutation:
    """Taegis Context_summarizer Mutation operations."""

    def __init__(self, service: ContextSummarizerService):
        self.service = service
