"""Sharelinks Subscription."""
# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from taegis_sdk_python.services.sharelinks.types import *

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.sharelinks import SharelinksService

log = logging.getLogger(__name__)


class TaegisSDKSharelinksSubscription:
    """Taegis Sharelinks Subscription operations."""

    def __init__(self, service: SharelinksService):
        self.service = service
