"""Sharelinks Types and Enums."""
# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code

# Autogenerated
# DO NOT MODIFY

from dataclasses import dataclass, field

from typing import Any, Dict, List, Optional, Tuple, Union

from dataclasses_json import config, dataclass_json


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ExtraParam:
    """ExtraParam."""

    key: Optional[str] = field(default=None, metadata=config(field_name="key"))
    value: Optional[str] = field(default=None, metadata=config(field_name="value"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ExtraParamCreateInput:
    """ExtraParamCreateInput."""

    key: Optional[str] = field(default=None, metadata=config(field_name="key"))
    value: Optional[str] = field(default=None, metadata=config(field_name="value"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ShareLink:
    """ShareLink."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    tenant_id: Optional[str] = field(
        default=None, metadata=config(field_name="tenantId")
    )
    link_type: Optional[str] = field(
        default=None, metadata=config(field_name="linkType")
    )
    link_ref: Optional[str] = field(default=None, metadata=config(field_name="linkRef"))
    link_target: Optional[str] = field(
        default=None, metadata=config(field_name="linkTarget")
    )
    event_type: Optional[str] = field(
        default=None, metadata=config(field_name="eventType")
    )
    created_time: Optional[str] = field(
        default=None, metadata=config(field_name="createdTime")
    )
    extra_parameters: Optional[List[ExtraParam]] = field(
        default=None, metadata=config(field_name="extraParameters")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ShareLinkCreateInput:
    """ShareLinkCreateInput."""

    tenant_id: Optional[str] = field(
        default=None, metadata=config(field_name="tenantId")
    )
    link_type: Optional[str] = field(
        default=None, metadata=config(field_name="linkType")
    )
    link_ref: Optional[str] = field(default=None, metadata=config(field_name="linkRef"))
    link_target: Optional[str] = field(
        default=None, metadata=config(field_name="linkTarget")
    )
    event_type: Optional[str] = field(
        default=None, metadata=config(field_name="eventType")
    )
    extra_parameters: Optional[List[ExtraParamCreateInput]] = field(
        default=None, metadata=config(field_name="extraParameters")
    )
