"""ThreatPublications Mutation."""
# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from taegis_sdk_python.services.threat_publications.types import *

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.threat_publications import ThreatPublicationsService

log = logging.getLogger(__name__)


class TaegisSDKThreatPublicationsMutation:
    """Taegis Threat_publications Mutation operations."""

    def __init__(self, service: ThreatPublicationsService):
        self.service = service
