"""ThreatPublications Query."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple, Union

from taegis_sdk_python import GraphQLNoRowsInResultSetError
from taegis_sdk_python._consts import TaegisEnum
from taegis_sdk_python.services.threat_publications.types import *
from taegis_sdk_python.utils import (
    build_output_string,
    parse_union_result,
    prepare_input,
)

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.threat_publications import ThreatPublicationsService

log = logging.getLogger(__name__)


class TaegisSDKThreatPublicationsQuery:
    """Taegis Threat_publications Query operations."""

    def __init__(self, service: ThreatPublicationsService):
        self.service = service

    def threat_publication(
        self,
        id_: str,
        content_format: Optional[Union[ContentFormat, TaegisEnum]] = None,
    ) -> ThreatPublication:
        """Retreives a publication by ID.."""
        endpoint = "threatPublication"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "ID": prepare_input(id_),
                "contentFormat": prepare_input(content_format),
            },
            output=build_output_string(
                ThreatPublication,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return ThreatPublication.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query threatPublication")

    def threat_publications(
        self,
        text: str,
        content_format: Optional[Union[ContentFormat, TaegisEnum]] = None,
    ) -> List[ThreatPublication]:
        """Searches publications for text.."""
        endpoint = "threatPublications"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "text": prepare_input(text),
                "contentFormat": prepare_input(content_format),
            },
            output=build_output_string(
                ThreatPublication,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return ThreatPublication.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query threatPublications")

    def threat_latest_publications(
        self,
        from_: int,
        size: int,
        content_format: Optional[Union[ContentFormat, TaegisEnum]] = None,
    ) -> List[ThreatPublication]:
        """Gets the latest publications from an offset with a size.."""
        endpoint = "threatLatestPublications"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "from": prepare_input(from_),
                "size": prepare_input(size),
                "contentFormat": prepare_input(content_format),
            },
            output=build_output_string(
                ThreatPublication,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return ThreatPublication.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query threatLatestPublications")

    def threat_publications_search(
        self,
        text: List[str],
        content_format: Optional[Union[ContentFormat, TaegisEnum]] = None,
    ) -> List[ThreatPublication]:
        """Searches publications for array of text.."""
        endpoint = "threatPublicationsSearch"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "text": prepare_input(text),
                "contentFormat": prepare_input(content_format),
            },
            output=build_output_string(
                ThreatPublication,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return ThreatPublication.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query threatPublicationsSearch")
