"""ThreatPublications Types and Enums."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code

# Autogenerated
# DO NOT MODIFY

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Union

from dataclasses_json import config, dataclass_json

from taegis_sdk_python._consts import TaegisEnum
from taegis_sdk_python.utils import decode_enum, encode_enum, parse_union_result


class languageType(str, Enum):
    """languageType."""

    EN = "EN"
    JA = "JA"


class ContentFormat(str, Enum):
    """ContentFormat."""

    MD = "MD"
    HTML = "HTML"
    TEXT = "TEXT"
    PDF = "PDF"


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatPublication:
    """ThreatPublication."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    type: Optional[str] = field(default=None, metadata=config(field_name="Type"))
    name: Optional[str] = field(default=None, metadata=config(field_name="Name"))
    description: Optional[str] = field(
        default=None, metadata=config(field_name="Description")
    )
    published: Optional[str] = field(
        default=None, metadata=config(field_name="Published")
    )
    content: Optional[str] = field(default=None, metadata=config(field_name="Content"))
    tlp: Optional[str] = field(default=None, metadata=config(field_name="TLP"))
    vid: Optional[str] = field(default=None, metadata=config(field_name="VID"))
    report_id: Optional[str] = field(
        default=None, metadata=config(field_name="ReportID")
    )
    reference: Optional[str] = field(
        default=None, metadata=config(field_name="Reference")
    )
    category: Optional[str] = field(
        default=None, metadata=config(field_name="Category")
    )
    language: Optional[str] = field(
        default=None, metadata=config(field_name="Language")
    )
    pdf_url: Optional[str] = field(default=None, metadata=config(field_name="PDFUrl"))
