"""QlSchemas Subscription."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple, Union

from taegis_sdk_python import GraphQLNoRowsInResultSetError
from taegis_sdk_python._consts import TaegisEnum
from taegis_sdk_python.services.ql_schemas.types import *
from taegis_sdk_python.utils import (
    build_output_string,
    parse_union_result,
    prepare_input,
)

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.ql_schemas import QlSchemasService

log = logging.getLogger(__name__)


class TaegisSDKQlSchemasSubscription:
    """Taegis Ql_schemas Subscription operations."""

    def __init__(self, service: QlSchemasService):
        self.service = service

    def validate_ql_queries_v1(
        self, query: str, schemas_query: Optional[QLQueryInputV1] = None
    ) -> List[QLQueryValidationResultV1]:
        """Validates a query string and returns a valid boolean or an error."""
        endpoint = "validateQLQueriesV1"

        result = self.service.execute_subscription(
            endpoint=endpoint,
            variables={
                "query": prepare_input(query),
                "schemasQuery": prepare_input(schemas_query),
            },
            output=build_output_string(
                QLQueryValidationResultV1,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if any(r.get(endpoint) for r in result):
            return QLQueryValidationResultV1.schema().load(
                [r.get(endpoint, {}) or {} for r in result], many=True
            )
        raise GraphQLNoRowsInResultSetError("for subscription validateQLQueriesV1")
