"""Notifications2 Mutation."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple, Union

from taegis_sdk_python import GraphQLNoRowsInResultSetError
from taegis_sdk_python._consts import TaegisEnum
from taegis_sdk_python.services.notifications2.types import *
from taegis_sdk_python.utils import (
    build_output_string,
    parse_union_result,
    prepare_input,
)

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.notifications2 import Notifications2Service

log = logging.getLogger(__name__)


class TaegisSDKNotifications2Mutation:
    """Taegis Notifications2 Mutation operations."""

    def __init__(self, service: Notifications2Service):
        self.service = service

    def create_email_notification(
        self, input_: CreateEmailNotificationInput
    ) -> NotificationV2:
        """Create new email notification."""
        endpoint = "createEmailNotification"

        log.warning(
            f"GraphQL Mutation `{endpoint}` is deprecated: 'Use createNotificationV2 instead'"
        )

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationV2,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationV2.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for mutation createEmailNotification")

    def read_notifications(
        self, input_: ReadNotificationsInput
    ) -> List[NotificationV2]:
        """Marks a list of notifications as read."""
        endpoint = "readNotifications"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationV2,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationV2.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for mutation readNotifications")

    def replay_email_notifications(
        self, input_: ReplayEmailNotificationInput
    ) -> NotificationsV2:
        """Replay email notifications."""
        endpoint = "replayEmailNotifications"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationsV2,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationsV2.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for mutation replayEmailNotifications")

    def create_notification_v2(self, input_: CreateNotificationInput) -> NotificationV2:
        """Create new notificationv2."""
        endpoint = "createNotificationV2"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationV2,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationV2.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for mutation createNotificationV2")

    def register_push_subscription(
        self, input_: RegisterPushSubscriptionInput
    ) -> PushSubscription:
        """None."""
        endpoint = "registerPushSubscription"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                PushSubscription,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return PushSubscription.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for mutation registerPushSubscription")

    def un_register_push_subscription(
        self, input_: UnRegisterPushSubscriptionInput
    ) -> PushSubscription:
        """None."""
        endpoint = "unRegisterPushSubscription"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                PushSubscription,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return PushSubscription.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for mutation unRegisterPushSubscription")

    def acknowledge_notification(
        self, input_: CreateAcknowledgmentInput
    ) -> NotificationAcknowledgment:
        """None."""
        endpoint = "acknowledgeNotification"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationAcknowledgment,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationAcknowledgment.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for mutation acknowledgeNotification")

    def create_notification_rule(
        self, input_: CreateNotificationRuleInput
    ) -> NotificationRule:
        """None."""
        endpoint = "createNotificationRule"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationRule,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationRule.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for mutation createNotificationRule")

    def update_notification_rule(
        self, input_: UpdateNotificationRuleInput
    ) -> NotificationRule:
        """None."""
        endpoint = "updateNotificationRule"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationRule,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationRule.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for mutation updateNotificationRule")

    def delete_notification_rule(
        self, input_: DeleteNotificationRuleInput
    ) -> NotificationRule:
        """None."""
        endpoint = "deleteNotificationRule"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationRule,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationRule.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for mutation deleteNotificationRule")

    def set_escalation_policy_for_notification_rule(
        self, input_: SetEscalationPolicyForNotificationRuleInput
    ) -> NotificationRule:
        """Set an escalation policy for a notification rule.
        A notification rule can only have one escalation policy at a time for a given tenant.
        Calling this endpoint will replace the existing escalation policy with the new one if one was present before..
        """
        endpoint = "setEscalationPolicyForNotificationRule"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationRule,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationRule.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError(
            "for mutation setEscalationPolicyForNotificationRule"
        )

    def remove_escalation_policy_from_notification_rule(
        self, input_: RemoveEscalationPolicyFromNotificationRuleInput
    ) -> NotificationRule:
        """Remove an escalation policy from a notification rule."""
        endpoint = "removeEscalationPolicyFromNotificationRule"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationRule,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationRule.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError(
            "for mutation removeEscalationPolicyFromNotificationRule"
        )

    def create_notification_templates_mapping(
        self, input_: CreateNotificationTemplatesMappingInput
    ) -> NotificationTemplatesMapping:
        """None."""
        endpoint = "createNotificationTemplatesMapping"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationTemplatesMapping,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationTemplatesMapping.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError(
            "for mutation createNotificationTemplatesMapping"
        )

    def create_notification_templates(
        self, input_: CreateNotificationTemplatesInput
    ) -> List[NotificationTemplate]:
        """None."""
        endpoint = "createNotificationTemplates"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationTemplate,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationTemplate.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for mutation createNotificationTemplates")

    def update_notification_templates_mapping(
        self, input_: UpdateNotificationTemplatesMappingInput
    ) -> NotificationTemplatesMapping:
        """None."""
        endpoint = "updateNotificationTemplatesMapping"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                NotificationTemplatesMapping,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationTemplatesMapping.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError(
            "for mutation updateNotificationTemplatesMapping"
        )

    def update_notification_templates(
        self, inputs: List[UpdateNotificationTemplateInput]
    ) -> List[NotificationTemplate]:
        """None."""
        endpoint = "updateNotificationTemplates"

        result = self.service.execute_mutation(
            endpoint=endpoint,
            variables={
                "inputs": prepare_input(inputs),
            },
            output=build_output_string(
                NotificationTemplate,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationTemplate.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for mutation updateNotificationTemplates")
