"""Notifications2 Query."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple, Union

from taegis_sdk_python import GraphQLNoRowsInResultSetError
from taegis_sdk_python._consts import TaegisEnum
from taegis_sdk_python.services.notifications2.types import *
from taegis_sdk_python.utils import (
    build_output_string,
    parse_union_result,
    prepare_input,
)

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.notifications2 import Notifications2Service

log = logging.getLogger(__name__)


class TaegisSDKNotifications2Query:
    """Taegis Notifications2 Query operations."""

    def __init__(self, service: Notifications2Service):
        self.service = service

    def notifications_v2(self, arguments: NotificationsV2Arguments) -> NotificationsV2:
        """notificationsV2 returns a list of notifications intended for the calling user.."""
        endpoint = "notificationsV2"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "arguments": prepare_input(arguments),
            },
            output=build_output_string(
                NotificationsV2,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationsV2.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query notificationsV2")

    def notification_v2(self, arguments: NotificationV2Arguments) -> NotificationV2:
        """notificationV2 returns a single notification by id. If the notification is not found, the service will return null.
        Will only return the last 60ish days of notifications.."""
        endpoint = "notificationV2"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "arguments": prepare_input(arguments),
            },
            output=build_output_string(
                NotificationV2,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationV2.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query notificationV2")

    def push_subscriptions(self) -> List[PushSubscription]:
        """pushSubscriptions returns a list of push subscriptions for the calling user.."""
        endpoint = "pushSubscriptions"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={},
            output=build_output_string(
                PushSubscription,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return PushSubscription.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query pushSubscriptions")

    def notification_rules(
        self, arguments: NotificationRulesArguments
    ) -> NotificationRules:
        """rules returns a list of rules.."""
        endpoint = "notificationRules"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "arguments": prepare_input(arguments),
            },
            output=build_output_string(
                NotificationRules,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationRules.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query notificationRules")

    def notification_rule(
        self, arguments: NotificationRuleArguments
    ) -> NotificationRule:
        """rule returns a single rule by id.."""
        endpoint = "notificationRule"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "arguments": prepare_input(arguments),
            },
            output=build_output_string(
                NotificationRule,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationRule.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query notificationRule")

    def notification_policy_assignments(
        self, arguments: Optional[NotificationEscalationsArguments] = None
    ) -> NotificationEscalations:
        """retrieve policy/rule assignments."""
        endpoint = "notificationPolicyAssignments"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "arguments": prepare_input(arguments),
            },
            output=build_output_string(
                NotificationEscalations,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationEscalations.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query notificationPolicyAssignments")

    def notifications_search(
        self, arguments: NotificationsSearchArguments
    ) -> NotificationsV2:
        """notificationsSearch returns a list of notifications based on the search arguments provided.."""
        endpoint = "notificationsSearch"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "arguments": prepare_input(arguments),
            },
            output=build_output_string(
                NotificationsV2,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationsV2.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query notificationsSearch")

    def notification_rule_source_details(self) -> List[NotificationRuleSourceDetails]:
        """notificationRuleSourceDetails returns the details of notification rule sources.."""
        endpoint = "notificationRuleSourceDetails"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={},
            output=build_output_string(
                NotificationRuleSourceDetails,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationRuleSourceDetails.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query notificationRuleSourceDetails")

    def notification_templates(
        self, arguments: NotificationTemplatesArguments
    ) -> NotificationTemplates:
        """None."""
        endpoint = "notificationTemplates"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "arguments": prepare_input(arguments),
            },
            output=build_output_string(
                NotificationTemplates,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NotificationTemplates.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query notificationTemplates")
