"""ThreatContext Types and Enums."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code

# Autogenerated
# DO NOT MODIFY

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Union

from dataclasses_json import config, dataclass_json

from taegis_sdk_python._consts import TaegisEnum
from taegis_sdk_python.utils import decode_enum, encode_enum, parse_union_result


class ThreatContextIndicatorType(str, Enum):
    """ThreatContextIndicatorType."""

    IP = "ip"
    DOMAIN = "domain"
    FILE = "file"
    URL = "url"


class OrderByOptions(str, Enum):
    """OrderByOptions."""

    ASC = "asc"
    DESC = "desc"


class CacheStyle(str, Enum):
    """CacheStyle."""

    ONLY = "only"
    FIRST = "first"
    LAST = "last"
    NEVER = "never"


class ThreatContextIntelixAnalysisType(str, Enum):
    """ThreatContextIntelixAnalysisType."""

    STATIC = "static"
    DYNAMIC = "dynamic"


class ThreatContextIntelixReportFormat(str, Enum):
    """ThreatContextIntelixReportFormat."""

    JSON = "json"
    HTML = "html"


class ThreatContextIntelixFileSubmissionType(str, Enum):
    """ThreatContextIntelixFileSubmissionType."""

    SAFESTORE = "safestore"
    ANALYSIS = "analysis"


class ThreatContextIntelixFileAnalysisStatus(str, Enum):
    """ThreatContextIntelixFileAnalysisStatus."""

    COMPLETE = "complete"
    SUBMISSION_IN_PROGRESS = "submissionInProgress"
    ANALYSIS_IN_PROGRESS = "analysisInProgress"
    FILE_TOO_LARGE = "fileTooLarge"
    FAILED = "failed"
    FILE_NOT_FOUND = "fileNotFound"
    SUBMISSION_TIMED_OUT = "submissionTimedOut"
    SUBMISSION_NOT_FOUND = "submissionNotFound"
    INTERNAL_ERROR = "internalError"
    ANALYSIS_TIMED_OUT = "analysisTimedOut"


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class CacheResults:
    """CacheResults."""

    last_updated: Optional[int] = field(
        default=None, metadata=config(field_name="last_updated")
    )
    last_updated_str: Optional[str] = field(
        default=None, metadata=config(field_name="last_updated_str")
    )
    found_in_cache: Optional[bool] = field(
        default=None, metadata=config(field_name="found_in_cache")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ReputationStats:
    """ReputationStats."""

    vt_harmless: Optional[int] = field(
        default=None, metadata=config(field_name="vt_harmless")
    )
    vt_malicious: Optional[int] = field(
        default=None, metadata=config(field_name="vt_malicious")
    )
    vt_suspicious: Optional[int] = field(
        default=None, metadata=config(field_name="vt_suspicious")
    )
    vt_undetected: Optional[int] = field(
        default=None, metadata=config(field_name="vt_undetected")
    )
    vt_timeout: Optional[int] = field(
        default=None, metadata=config(field_name="vt_timeout")
    )
    apivoid_detections: Optional[int] = field(
        default=None, metadata=config(field_name="apivoid_detections")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidStats:
    """APIVoidStats."""

    credits_remained: Optional[float] = field(
        default=None, metadata=config(field_name="credits_remained")
    )
    estimated_queries: Optional[str] = field(
        default=None,
        metadata=config(
            metadata={
                "deprecated": True,
                "deprecation_reason": "no longer supported as part of APIVoidV2",
            },
            field_name="estimated_queries",
        ),
    )
    error: Optional[str] = field(default=None, metadata=config(field_name="error"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIndicatorInput:
    """ThreatContextIndicatorInput."""

    indicator: Optional[str] = field(
        default=None, metadata=config(field_name="indicator")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ReputationOptions:
    """ReputationOptions."""

    apivoid_include_domain_age: Optional[bool] = field(
        default=None, metadata=config(field_name="apivoid_include_domain_age")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class IndicatorsSummary:
    """IndicatorsSummary."""

    indicators: Optional[List[str]] = field(
        default=None, metadata=config(field_name="indicators")
    )
    summary: Optional[str] = field(default=None, metadata=config(field_name="summary"))
    error: Optional[str] = field(default=None, metadata=config(field_name="error"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIntelixReport:
    """ThreatContextIntelixReport."""

    report: Optional[str] = field(default=None, metadata=config(field_name="report"))
    error: Optional[str] = field(default=None, metadata=config(field_name="error"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIntelixGetLatestFileSubmissionInput:
    """ThreatContextIntelixGetLatestFileSubmissionInput."""

    sha256: Optional[str] = field(default=None, metadata=config(field_name="sha256"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalCategories:
    """VirusTotalCategories."""

    forcepoint_threat_seeker: Optional[str] = field(
        default=None, metadata=config(field_name="ForcepointThreatSeeker")
    )
    bit_defender: Optional[str] = field(
        default=None, metadata=config(field_name="BitDefender")
    )
    comodo_valkyrie_verdict: Optional[str] = field(
        default=None, metadata=config(field_name="ComodoValkyrieVerdict")
    )
    alpha_mountainai: Optional[str] = field(
        default=None, metadata=config(field_name="alphaMountainai")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalCertIssuer:
    """VirusTotalCertIssuer."""

    c: Optional[str] = field(default=None, metadata=config(field_name="C"))
    l: Optional[str] = field(default=None, metadata=config(field_name="L"))
    cn: Optional[str] = field(default=None, metadata=config(field_name="CN"))
    o: Optional[str] = field(default=None, metadata=config(field_name="O"))
    st: Optional[str] = field(default=None, metadata=config(field_name="ST"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalCertSignature:
    """VirusTotalCertSignature."""

    signature_algorithm: Optional[str] = field(
        default=None, metadata=config(field_name="signature_algorithm")
    )
    signature: Optional[str] = field(
        default=None, metadata=config(field_name="signature")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalCaInformationAccess:
    """VirusTotalCaInformationAccess."""

    caissuers: Optional[str] = field(
        default=None, metadata=config(field_name="CAIssuers")
    )
    ocsp: Optional[str] = field(default=None, metadata=config(field_name="OCSP"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalAuthorityKeyIdentifier:
    """VirusTotalAuthorityKeyIdentifier."""

    keyid: Optional[str] = field(default=None, metadata=config(field_name="keyid"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalValidity:
    """VirusTotalValidity."""

    not_after: Optional[str] = field(
        default=None, metadata=config(field_name="not_after")
    )
    not_before: Optional[str] = field(
        default=None, metadata=config(field_name="not_before")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalSubject:
    """VirusTotalSubject."""

    cn: Optional[str] = field(default=None, metadata=config(field_name="CN"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalRsa:
    """VirusTotalRsa."""

    key_size: Optional[int] = field(
        default=None, metadata=config(field_name="key_size")
    )
    modulus: Optional[str] = field(default=None, metadata=config(field_name="modulus"))
    exponent: Optional[str] = field(
        default=None, metadata=config(field_name="exponent")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalCiscoUmbrella:
    """VirusTotalCiscoUmbrella."""

    timestamp: Optional[int] = field(
        default=None, metadata=config(field_name="timestamp")
    )
    rank: Optional[int] = field(default=None, metadata=config(field_name="rank"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalAlexa:
    """VirusTotalAlexa."""

    timestamp: Optional[int] = field(
        default=None, metadata=config(field_name="timestamp")
    )
    rank: Optional[int] = field(default=None, metadata=config(field_name="rank"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalStatvoo:
    """VirusTotalStatvoo."""

    timestamp: Optional[int] = field(
        default=None, metadata=config(field_name="timestamp")
    )
    rank: Optional[int] = field(default=None, metadata=config(field_name="rank"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalMajestic:
    """VirusTotalMajestic."""

    timestamp: Optional[int] = field(
        default=None, metadata=config(field_name="timestamp")
    )
    rank: Optional[int] = field(default=None, metadata=config(field_name="rank"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalLastDnsRecords:
    """VirusTotalLastDnsRecords."""

    rname: Optional[str] = field(default=None, metadata=config(field_name="rname"))
    retry: Optional[int] = field(default=None, metadata=config(field_name="retry"))
    refresh: Optional[int] = field(default=None, metadata=config(field_name="refresh"))
    minimum: Optional[int] = field(default=None, metadata=config(field_name="minimum"))
    value: Optional[str] = field(default=None, metadata=config(field_name="value"))
    expire: Optional[int] = field(default=None, metadata=config(field_name="expire"))
    ttl: Optional[int] = field(default=None, metadata=config(field_name="ttl"))
    serial: Optional[int] = field(default=None, metadata=config(field_name="serial"))
    type: Optional[str] = field(default=None, metadata=config(field_name="type"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalEngine:
    """VirusTotalEngine."""

    category: Optional[str] = field(
        default=None, metadata=config(field_name="category")
    )
    result: Optional[str] = field(default=None, metadata=config(field_name="result"))
    method: Optional[str] = field(default=None, metadata=config(field_name="method"))
    engine_name: Optional[str] = field(
        default=None, metadata=config(field_name="engine_name")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalLinks:
    """VirusTotalLinks."""

    self: Optional[str] = field(default=None, metadata=config(field_name="self"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalTotalVotes:
    """VirusTotalTotalVotes."""

    harmless: Optional[int] = field(
        default=None, metadata=config(field_name="harmless")
    )
    malicious: Optional[int] = field(
        default=None, metadata=config(field_name="malicious")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalLastAnalysisStats:
    """VirusTotalLastAnalysisStats."""

    harmless: Optional[int] = field(
        default=None, metadata=config(field_name="harmless")
    )
    malicious: Optional[int] = field(
        default=None, metadata=config(field_name="malicious")
    )
    suspicious: Optional[int] = field(
        default=None, metadata=config(field_name="suspicious")
    )
    undetected: Optional[int] = field(
        default=None, metadata=config(field_name="undetected")
    )
    timeout: Optional[int] = field(default=None, metadata=config(field_name="timeout"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class KeyValuePair:
    """KeyValuePair."""

    name: Optional[str] = field(default=None, metadata=config(field_name="name"))
    value: Optional[str] = field(default=None, metadata=config(field_name="value"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalFavicon:
    """VirusTotalFavicon."""

    key: Optional[str] = field(default=None, metadata=config(field_name="key"))
    dhash: Optional[str] = field(default=None, metadata=config(field_name="dhash"))
    raw_md5: Optional[str] = field(default=None, metadata=config(field_name="raw_md5"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalURLTracker:
    """VirusTotalURLTracker."""

    name: Optional[str] = field(default=None, metadata=config(field_name="name"))
    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    timestamp: Optional[int] = field(
        default=None, metadata=config(field_name="timestamp")
    )
    url: Optional[str] = field(default=None, metadata=config(field_name="url"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalCrowdsourcedContext:
    """VirusTotalCrowdsourcedContext."""

    source: Optional[str] = field(default=None, metadata=config(field_name="source"))
    title: Optional[str] = field(default=None, metadata=config(field_name="title"))
    detail: Optional[str] = field(default=None, metadata=config(field_name="detail"))
    severity: Optional[str] = field(
        default=None, metadata=config(field_name="severity")
    )
    timestamp: Optional[int] = field(
        default=None, metadata=config(field_name="timestamp")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalFileEngine:
    """VirusTotalFileEngine."""

    category: Optional[str] = field(
        default=None, metadata=config(field_name="category")
    )
    engine_name: Optional[str] = field(
        default=None, metadata=config(field_name="engine_name")
    )
    engine_version: Optional[str] = field(
        default=None, metadata=config(field_name="engine_version")
    )
    result: Optional[str] = field(default=None, metadata=config(field_name="result"))
    method: Optional[str] = field(default=None, metadata=config(field_name="method"))
    engine_update: Optional[str] = field(
        default=None, metadata=config(field_name="engine_update")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalExiftool:
    """VirusTotalExiftool."""

    mime_type: Optional[str] = field(
        default=None, metadata=config(field_name="MIMEType")
    )
    file_type: Optional[str] = field(
        default=None, metadata=config(field_name="FileType")
    )
    word_count: Optional[str] = field(
        default=None, metadata=config(field_name="WordCount")
    )
    line_count: Optional[str] = field(
        default=None, metadata=config(field_name="LineCount")
    )
    mime_encoding: Optional[str] = field(
        default=None, metadata=config(field_name="MIMEEncoding")
    )
    file_type_extension: Optional[str] = field(
        default=None, metadata=config(field_name="FileTypeExtension")
    )
    newlines: Optional[str] = field(
        default=None, metadata=config(field_name="Newlines")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalLastFileAnalysisStats:
    """VirusTotalLastFileAnalysisStats."""

    harmless: Optional[int] = field(
        default=None, metadata=config(field_name="harmless")
    )
    typeunsupported: Optional[int] = field(
        default=None, metadata=config(field_name="typeunsupported")
    )
    suspicious: Optional[int] = field(
        default=None, metadata=config(field_name="suspicious")
    )
    confirmedtimeout: Optional[int] = field(
        default=None, metadata=config(field_name="confirmedtimeout")
    )
    timeout: Optional[int] = field(default=None, metadata=config(field_name="timeout"))
    failure: Optional[int] = field(default=None, metadata=config(field_name="failure"))
    malicious: Optional[int] = field(
        default=None, metadata=config(field_name="malicious")
    )
    undetected: Optional[int] = field(
        default=None, metadata=config(field_name="undetected")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalOsxSandbox:
    """VirusTotalOsxSandbox."""

    category: Optional[str] = field(
        default=None, metadata=config(field_name="category")
    )
    sandbox_name: Optional[str] = field(
        default=None, metadata=config(field_name="sandbox_name")
    )
    malware_classification: Optional[List[str]] = field(
        default=None, metadata=config(field_name="malware_classification")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalLastline:
    """VirusTotalLastline."""

    category: Optional[str] = field(
        default=None, metadata=config(field_name="category")
    )
    sandbox_name: Optional[str] = field(
        default=None, metadata=config(field_name="sandbox_name")
    )
    malware_classification: Optional[List[str]] = field(
        default=None, metadata=config(field_name="malware_classification")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalKnownDistributors:
    """VirusTotalKnownDistributors."""

    data_sources: Optional[List[str]] = field(
        default=None, metadata=config(field_name="data_sources")
    )
    distributors: Optional[List[str]] = field(
        default=None, metadata=config(field_name="distributors")
    )
    products: Optional[List[str]] = field(
        default=None, metadata=config(field_name="products")
    )
    filenames: Optional[List[str]] = field(
        default=None, metadata=config(field_name="filenames")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalPopularThreatName:
    """VirusTotalPopularThreatName."""

    count: Optional[int] = field(default=None, metadata=config(field_name="count"))
    value: Optional[str] = field(default=None, metadata=config(field_name="value"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalPopularThreatCategory:
    """VirusTotalPopularThreatCategory."""

    count: Optional[int] = field(default=None, metadata=config(field_name="count"))
    value: Optional[str] = field(default=None, metadata=config(field_name="value"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalCrowdsourcedYaraResults:
    """VirusTotalCrowdsourcedYaraResults."""

    description: Optional[str] = field(
        default=None, metadata=config(field_name="description")
    )
    source: Optional[str] = field(default=None, metadata=config(field_name="source"))
    author: Optional[str] = field(default=None, metadata=config(field_name="author"))
    ruleset_name: Optional[str] = field(
        default=None, metadata=config(field_name="ruleset_name")
    )
    rule_name: Optional[str] = field(
        default=None, metadata=config(field_name="rule_name")
    )
    ruleset_id: Optional[str] = field(
        default=None, metadata=config(field_name="ruleset_id")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class Trid:
    """Trid."""

    file_type: Optional[str] = field(
        default=None, metadata=config(field_name="file_type")
    )
    probability: Optional[int] = field(
        default=None, metadata=config(field_name="probability")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalAutostartLocations:
    """VirusTotalAutostartLocations."""

    entry: Optional[str] = field(default=None, metadata=config(field_name="entry"))
    location: Optional[str] = field(
        default=None, metadata=config(field_name="location")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class BigBirdDomainContext:
    """BigBirdDomainContext."""

    academia: Optional[bool] = field(
        default=None, metadata=config(field_name="academia")
    )
    captive_portal: Optional[bool] = field(
        default=None, metadata=config(field_name="captive_portal")
    )
    crl: Optional[bool] = field(default=None, metadata=config(field_name="crl"))
    ddns: Optional[bool] = field(default=None, metadata=config(field_name="ddns"))
    disposable_email_service: Optional[bool] = field(
        default=None, metadata=config(field_name="disposable_email_service")
    )
    managed_service: Optional[bool] = field(
        default=None, metadata=config(field_name="managed_service")
    )
    newly_registered_domain: Optional[bool] = field(
        default=None, metadata=config(field_name="newly_registered_domain")
    )
    public_dns_resolver: Optional[bool] = field(
        default=None, metadata=config(field_name="public_dns_resolver")
    )
    reserved: Optional[bool] = field(
        default=None, metadata=config(field_name="reserved")
    )
    telemetry: Optional[bool] = field(
        default=None, metadata=config(field_name="telemetry")
    )
    tld: Optional[str] = field(default=None, metadata=config(field_name="tld"))
    top_domain: Optional[bool] = field(
        default=None, metadata=config(field_name="top_domain")
    )
    url_shortener: Optional[bool] = field(
        default=None, metadata=config(field_name="url_shortener")
    )
    valid_tld: Optional[bool] = field(
        default=None, metadata=config(field_name="valid_tld")
    )
    first_seen: Optional[int] = field(
        default=None, metadata=config(field_name="first_seen")
    )
    last_seen: Optional[int] = field(
        default=None, metadata=config(field_name="last_seen")
    )
    related: Optional[List[str]] = field(
        default=None, metadata=config(field_name="related")
    )
    services: Optional[List[str]] = field(
        default=None, metadata=config(field_name="services")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class BigBirdAsn:
    """BigBirdAsn."""

    asn: Optional[str] = field(default=None, metadata=config(field_name="asn"))
    name: Optional[str] = field(default=None, metadata=config(field_name="name"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class BigBirdLocation:
    """BigBirdLocation."""

    lat: Optional[float] = field(default=None, metadata=config(field_name="lat"))
    lon: Optional[float] = field(default=None, metadata=config(field_name="lon"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class BigBirdIPContext:
    """BigBirdIPContext."""

    hosting: Optional[bool] = field(default=None, metadata=config(field_name="hosting"))
    proxy: Optional[bool] = field(default=None, metadata=config(field_name="proxy"))
    relay: Optional[bool] = field(default=None, metadata=config(field_name="relay"))
    reserved: Optional[bool] = field(
        default=None, metadata=config(field_name="reserved")
    )
    scanning: Optional[bool] = field(
        default=None, metadata=config(field_name="scanning")
    )
    tor: Optional[bool] = field(default=None, metadata=config(field_name="tor"))
    vpn: Optional[bool] = field(default=None, metadata=config(field_name="vpn"))
    first_seen: Optional[int] = field(
        default=None, metadata=config(field_name="first_seen")
    )
    last_seen: Optional[int] = field(
        default=None, metadata=config(field_name="last_seen")
    )
    related: Optional[List[str]] = field(
        default=None, metadata=config(field_name="related")
    )
    services: Optional[List[str]] = field(
        default=None, metadata=config(field_name="services")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class BigBirdFileContext:
    """BigBirdFileContext."""

    nsrl: Optional[bool] = field(default=None, metadata=config(field_name="nsrl"))
    alternative_hashes: Optional[List[str]] = field(
        default=None, metadata=config(field_name="alternative_hashes")
    )
    detonated_in_atlas: Optional[bool] = field(
        default=None, metadata=config(field_name="detonated_in_atlas")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidCategory:
    """APIVoidCategory."""

    is_free_hosting: Optional[bool] = field(
        default=None, metadata=config(field_name="is_free_hosting")
    )
    is_anonymizer: Optional[bool] = field(
        default=None, metadata=config(field_name="is_anonymizer")
    )
    is_url_shortener: Optional[bool] = field(
        default=None, metadata=config(field_name="is_url_shortener")
    )
    is_free_dynamic_dns: Optional[bool] = field(
        default=None, metadata=config(field_name="is_free_dynamic_dns")
    )
    is_code_sandbox: Optional[bool] = field(
        default=None, metadata=config(field_name="is_code_sandbox")
    )
    is_form_builder: Optional[bool] = field(
        default=None, metadata=config(field_name="is_form_builder")
    )
    is_free_file_sharing: Optional[bool] = field(
        default=None, metadata=config(field_name="is_free_file_sharing")
    )
    is_pastebin: Optional[bool] = field(
        default=None, metadata=config(field_name="is_pastebin")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidServer:
    """APIVoidServer."""

    ip: Optional[str] = field(default=None, metadata=config(field_name="ip"))
    reverse_dns: Optional[str] = field(
        default=None, metadata=config(field_name="reverse_dns")
    )
    continent_code: Optional[str] = field(
        default=None, metadata=config(field_name="continent_code")
    )
    continent_name: Optional[str] = field(
        default=None, metadata=config(field_name="continent_name")
    )
    country_code: Optional[str] = field(
        default=None, metadata=config(field_name="country_code")
    )
    country_name: Optional[str] = field(
        default=None, metadata=config(field_name="country_name")
    )
    region_name: Optional[str] = field(
        default=None, metadata=config(field_name="region_name")
    )
    city_name: Optional[str] = field(
        default=None, metadata=config(field_name="city_name")
    )
    latitude: Optional[float] = field(
        default=None, metadata=config(field_name="latitude")
    )
    longitude: Optional[float] = field(
        default=None, metadata=config(field_name="longitude")
    )
    isp: Optional[str] = field(default=None, metadata=config(field_name="isp"))
    asn: Optional[str] = field(default=None, metadata=config(field_name="asn"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidDomainParts:
    """APIVoidDomainParts."""

    root_domain: Optional[str] = field(
        default=None, metadata=config(field_name="root_domain")
    )
    subdomain: Optional[str] = field(
        default=None, metadata=config(field_name="subdomain")
    )
    tld: Optional[str] = field(default=None, metadata=config(field_name="tld"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidDomainSecurityChecks:
    """APIVoidDomainSecurityChecks."""

    is_most_abused_tld: Optional[bool] = field(
        default=None, metadata=config(field_name="is_most_abused_tld")
    )
    is_domain_ipv4_assigned: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_assigned")
    )
    is_domain_ipv4_private: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_private")
    )
    is_domain_ipv4_loopback: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_loopback")
    )
    is_domain_ipv4_reserved: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_reserved")
    )
    is_domain_ipv4_valid: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_valid")
    )
    is_domain_blacklisted: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_blacklisted")
    )
    is_uncommon_host_length: Optional[bool] = field(
        default=None, metadata=config(field_name="is_uncommon_host_length")
    )
    is_uncommon_dash_char_count: Optional[bool] = field(
        default=None, metadata=config(field_name="is_uncommon_dash_char_count")
    )
    is_uncommon_dot_char_count: Optional[bool] = field(
        default=None, metadata=config(field_name="is_uncommon_dot_char_count")
    )
    website_popularity: Optional[str] = field(
        default=None, metadata=config(field_name="website_popularity")
    )
    is_uncommon_clickable_domain: Optional[bool] = field(
        default=None, metadata=config(field_name="is_uncommon_clickable_domain")
    )
    is_risky_category: Optional[bool] = field(
        default=None, metadata=config(field_name="is_risky_category")
    )
    detections_count: Optional[int] = field(
        default=None, metadata=config(field_name="detections_count")
    )
    is_suspicious_homoglyph: Optional[bool] = field(
        default=None, metadata=config(field_name="is_suspicious_homoglyph")
    )
    is_possible_typosquatting: Optional[bool] = field(
        default=None, metadata=config(field_name="is_possible_typosquatting")
    )
    is_domain_recent: Optional[str] = field(
        default=None, metadata=config(field_name="is_domain_recent")
    )
    is_domain_very_recent: Optional[str] = field(
        default=None, metadata=config(field_name="is_domain_very_recent")
    )
    domain_creation_date: Optional[str] = field(
        default=None, metadata=config(field_name="domain_creation_date")
    )
    domain_age_in_days: Optional[int] = field(
        default=None, metadata=config(field_name="domain_age_in_days")
    )
    domain_age_in_months: Optional[int] = field(
        default=None, metadata=config(field_name="domain_age_in_months")
    )
    domain_age_in_years: Optional[int] = field(
        default=None, metadata=config(field_name="domain_age_in_years")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidDNSRecord:
    """APIVoidDNSRecord."""

    target: Optional[str] = field(default=None, metadata=config(field_name="target"))
    ip: Optional[str] = field(default=None, metadata=config(field_name="ip"))
    country_code: Optional[str] = field(
        default=None, metadata=config(field_name="country_code")
    )
    country_name: Optional[str] = field(
        default=None, metadata=config(field_name="country_name")
    )
    isp: Optional[str] = field(default=None, metadata=config(field_name="isp"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidURLEngine:
    """APIVoidURLEngine."""

    name: Optional[str] = field(default=None, metadata=config(field_name="name"))
    reference: Optional[str] = field(
        default=None, metadata=config(field_name="reference")
    )
    detected: Optional[bool] = field(
        default=None, metadata=config(field_name="detected")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidFileType:
    """APIVoidFileType."""

    signature: Optional[str] = field(
        default=None, metadata=config(field_name="signature")
    )
    extension: Optional[str] = field(
        default=None, metadata=config(field_name="extension")
    )
    headers: Optional[str] = field(default=None, metadata=config(field_name="headers"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidGeoLocation:
    """APIVoidGeoLocation."""

    countries: Optional[List[str]] = field(
        default=None, metadata=config(field_name="countries")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidHTMLForms:
    """APIVoidHTMLForms."""

    number_of_total_forms: Optional[int] = field(
        default=None, metadata=config(field_name="number_of_total_forms")
    )
    number_of_total_input_fields: Optional[int] = field(
        default=None, metadata=config(field_name="number_of_total_input_fields")
    )
    two_text_inputs_in_a_form: Optional[bool] = field(
        default=None, metadata=config(field_name="two_text_inputs_in_a_form")
    )
    credit_card_field_present: Optional[bool] = field(
        default=None, metadata=config(field_name="credit_card_field_present")
    )
    password_field_present: Optional[bool] = field(
        default=None, metadata=config(field_name="password_field_present")
    )
    email_field_present: Optional[bool] = field(
        default=None, metadata=config(field_name="email_field_present")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidRedirection:
    """APIVoidRedirection."""

    found: Optional[bool] = field(default=None, metadata=config(field_name="found"))
    external: Optional[bool] = field(
        default=None, metadata=config(field_name="external")
    )
    url: Optional[str] = field(default=None, metadata=config(field_name="url"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidURLSecurityChecks:
    """APIVoidURLSecurityChecks."""

    is_host_an_ipv4: Optional[bool] = field(
        default=None, metadata=config(field_name="is_host_an_ipv4")
    )
    is_uncommon_host_length: Optional[bool] = field(
        default=None, metadata=config(field_name="is_uncommon_host_length")
    )
    is_uncommon_dash_char_count: Optional[bool] = field(
        default=None, metadata=config(field_name="is_uncommon_dash_char_count")
    )
    is_uncommon_dot_char_count: Optional[bool] = field(
        default=None, metadata=config(field_name="is_uncommon_dot_char_count")
    )
    is_suspicious_url_pattern: Optional[bool] = field(
        default=None, metadata=config(field_name="is_suspicious_url_pattern")
    )
    is_suspicious_file_extension: Optional[bool] = field(
        default=None, metadata=config(field_name="is_suspicious_file_extension")
    )
    is_robots_noindex: Optional[bool] = field(
        default=None, metadata=config(field_name="is_robots_noindex")
    )
    is_suspended_page: Optional[bool] = field(
        default=None, metadata=config(field_name="is_suspended_page")
    )
    is_most_abused_tld: Optional[bool] = field(
        default=None, metadata=config(field_name="is_most_abused_tld")
    )
    is_uncommon_clickable_url: Optional[bool] = field(
        default=None, metadata=config(field_name="is_uncommon_clickable_url")
    )
    is_phishing_heuristic: Optional[bool] = field(
        default=None, metadata=config(field_name="is_phishing_heuristic")
    )
    is_possible_emotet: Optional[bool] = field(
        default=None, metadata=config(field_name="is_possible_emotet")
    )
    is_redirect_to_search_engine: Optional[bool] = field(
        default=None, metadata=config(field_name="is_redirect_to_search_engine")
    )
    is_http_status_error: Optional[bool] = field(
        default=None, metadata=config(field_name="is_http_status_error")
    )
    is_http_server_error: Optional[bool] = field(
        default=None, metadata=config(field_name="is_http_server_error")
    )
    is_http_client_error: Optional[bool] = field(
        default=None, metadata=config(field_name="is_http_client_error")
    )
    is_suspicious_content: Optional[bool] = field(
        default=None, metadata=config(field_name="is_suspicious_content")
    )
    is_url_accessible: Optional[bool] = field(
        default=None, metadata=config(field_name="is_url_accessible")
    )
    is_empty_page_title: Optional[bool] = field(
        default=None, metadata=config(field_name="is_empty_page_title")
    )
    is_empty_page_content: Optional[bool] = field(
        default=None, metadata=config(field_name="is_empty_page_content")
    )
    is_domain_ipv4_assigned: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_assigned")
    )
    is_domain_ipv4_private: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_private")
    )
    is_domain_ipv4_loopback: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_loopback")
    )
    is_domain_ipv4_reserved: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_reserved")
    )
    is_domain_ipv4_valid: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_ipv4_valid")
    )
    is_domain_blacklisted: Optional[bool] = field(
        default=None, metadata=config(field_name="is_domain_blacklisted")
    )
    is_suspicious_domain: Optional[bool] = field(
        default=None, metadata=config(field_name="is_suspicious_domain")
    )
    is_sinkholed_domain: Optional[bool] = field(
        default=None, metadata=config(field_name="is_sinkholed_domain")
    )
    is_defaced_heuristic: Optional[bool] = field(
        default=None, metadata=config(field_name="is_defaced_heuristic")
    )
    is_masked_file: Optional[bool] = field(
        default=None, metadata=config(field_name="is_masked_file")
    )
    is_risky_geo_location: Optional[bool] = field(
        default=None, metadata=config(field_name="is_risky_geo_location")
    )
    is_china_country: Optional[bool] = field(
        default=None, metadata=config(field_name="is_china_country")
    )
    is_nigeria_country: Optional[bool] = field(
        default=None, metadata=config(field_name="is_nigeria_country")
    )
    is_non_standard_port: Optional[bool] = field(
        default=None, metadata=config(field_name="is_non_standard_port")
    )
    is_email_address_on_url_query: Optional[bool] = field(
        default=None, metadata=config(field_name="is_email_address_on_url_query")
    )
    is_directory_listing: Optional[bool] = field(
        default=None, metadata=config(field_name="is_directory_listing")
    )
    is_exe_on_directory_listing: Optional[bool] = field(
        default=None, metadata=config(field_name="is_exe_on_directory_listing")
    )
    is_zip_on_directory_listing: Optional[bool] = field(
        default=None, metadata=config(field_name="is_zip_on_directory_listing")
    )
    is_php_on_directory_listing: Optional[bool] = field(
        default=None, metadata=config(field_name="is_php_on_directory_listing")
    )
    is_doc_on_directory_listing: Optional[bool] = field(
        default=None, metadata=config(field_name="is_doc_on_directory_listing")
    )
    is_pdf_on_directory_listing: Optional[bool] = field(
        default=None, metadata=config(field_name="is_pdf_on_directory_listing")
    )
    is_apk_on_directory_listing: Optional[bool] = field(
        default=None, metadata=config(field_name="is_apk_on_directory_listing")
    )
    is_linux_elf_file: Optional[bool] = field(
        default=None, metadata=config(field_name="is_linux_elf_file")
    )
    is_linux_elf_file_on_free_dynamic_dns: Optional[bool] = field(
        default=None,
        metadata=config(field_name="is_linux_elf_file_on_free_dynamic_dns"),
    )
    is_linux_elf_file_on_free_hosting: Optional[bool] = field(
        default=None, metadata=config(field_name="is_linux_elf_file_on_free_hosting")
    )
    is_linux_elf_file_on_ipv4: Optional[bool] = field(
        default=None, metadata=config(field_name="is_linux_elf_file_on_ipv4")
    )
    is_masked_linux_elf_file: Optional[bool] = field(
        default=None, metadata=config(field_name="is_masked_linux_elf_file")
    )
    is_masked_windows_exe_file: Optional[bool] = field(
        default=None, metadata=config(field_name="is_masked_windows_exe_file")
    )
    is_ms_office_file: Optional[bool] = field(
        default=None, metadata=config(field_name="is_ms_office_file")
    )
    is_windows_exe_file_on_free_dynamic_dns: Optional[bool] = field(
        default=None,
        metadata=config(field_name="is_windows_exe_file_on_free_dynamic_dns"),
    )
    is_windows_exe_file_on_free_hosting: Optional[bool] = field(
        default=None, metadata=config(field_name="is_windows_exe_file_on_free_hosting")
    )
    is_windows_exe_file_on_ipv4: Optional[bool] = field(
        default=None, metadata=config(field_name="is_windows_exe_file_on_ipv4")
    )
    is_windows_exe_file: Optional[bool] = field(
        default=None, metadata=config(field_name="is_windows_exe_file")
    )
    is_android_apk_file_on_free_dynamic_dns: Optional[bool] = field(
        default=None,
        metadata=config(field_name="is_android_apk_file_on_free_dynamic_dns"),
    )
    is_android_apk_file_on_free_hosting: Optional[bool] = field(
        default=None, metadata=config(field_name="is_android_apk_file_on_free_hosting")
    )
    is_android_apk_file_on_ipv4: Optional[bool] = field(
        default=None, metadata=config(field_name="is_android_apk_file_on_ipv4")
    )
    is_android_apk_file: Optional[bool] = field(
        default=None, metadata=config(field_name="is_android_apk_file")
    )
    is_external_redirect: Optional[bool] = field(
        default=None, metadata=config(field_name="is_external_redirect")
    )
    is_risky_category: Optional[bool] = field(
        default=None, metadata=config(field_name="is_risky_category")
    )
    is_domain_recent: Optional[str] = field(
        default=None, metadata=config(field_name="is_domain_recent")
    )
    is_domain_very_recent: Optional[str] = field(
        default=None, metadata=config(field_name="is_domain_very_recent")
    )
    is_credit_card_field: Optional[bool] = field(
        default=None, metadata=config(field_name="is_credit_card_field")
    )
    is_password_field: Optional[bool] = field(
        default=None, metadata=config(field_name="is_password_field")
    )
    is_valid_https: Optional[bool] = field(
        default=None, metadata=config(field_name="is_valid_https")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidServerDetails:
    """APIVoidServerDetails."""

    ip: Optional[str] = field(default=None, metadata=config(field_name="ip"))
    hostname: Optional[str] = field(
        default=None, metadata=config(field_name="hostname")
    )
    continent_code: Optional[str] = field(
        default=None, metadata=config(field_name="continent_code")
    )
    continent_name: Optional[str] = field(
        default=None, metadata=config(field_name="continent_name")
    )
    country_code: Optional[str] = field(
        default=None, metadata=config(field_name="country_code")
    )
    country_name: Optional[str] = field(
        default=None, metadata=config(field_name="country_name")
    )
    region_name: Optional[str] = field(
        default=None, metadata=config(field_name="region_name")
    )
    city_name: Optional[str] = field(
        default=None, metadata=config(field_name="city_name")
    )
    latitude: Optional[float] = field(
        default=None, metadata=config(field_name="latitude")
    )
    longitude: Optional[float] = field(
        default=None, metadata=config(field_name="longitude")
    )
    isp: Optional[str] = field(default=None, metadata=config(field_name="isp"))
    asn: Optional[str] = field(default=None, metadata=config(field_name="asn"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidSiteCategory:
    """APIVoidSiteCategory."""

    is_torrent: Optional[bool] = field(
        default=None, metadata=config(field_name="is_torrent")
    )
    is_vpn_provider: Optional[bool] = field(
        default=None, metadata=config(field_name="is_vpn_provider")
    )
    is_free_hosting: Optional[bool] = field(
        default=None, metadata=config(field_name="is_free_hosting")
    )
    is_anonymizer: Optional[bool] = field(
        default=None, metadata=config(field_name="is_anonymizer")
    )
    is_url_shortener: Optional[bool] = field(
        default=None, metadata=config(field_name="is_url_shortener")
    )
    is_free_dynamic_dns: Optional[bool] = field(
        default=None, metadata=config(field_name="is_free_dynamic_dns")
    )
    is_code_sandbox: Optional[bool] = field(
        default=None, metadata=config(field_name="is_code_sandbox")
    )
    is_form_builder: Optional[bool] = field(
        default=None, metadata=config(field_name="is_form_builder")
    )
    is_free_file_sharing: Optional[bool] = field(
        default=None, metadata=config(field_name="is_free_file_sharing")
    )
    is_pastebin: Optional[bool] = field(
        default=None, metadata=config(field_name="is_pastebin")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidURLParts:
    """APIVoidURLParts."""

    scheme: Optional[str] = field(default=None, metadata=config(field_name="scheme"))
    host: Optional[str] = field(default=None, metadata=config(field_name="host"))
    host_nowww: Optional[str] = field(
        default=None, metadata=config(field_name="host_nowww")
    )
    port: Optional[str] = field(default=None, metadata=config(field_name="port"))
    path: Optional[str] = field(default=None, metadata=config(field_name="path"))
    query: Optional[str] = field(default=None, metadata=config(field_name="query"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidWebPage:
    """APIVoidWebPage."""

    title: Optional[str] = field(default=None, metadata=config(field_name="title"))
    description: Optional[str] = field(
        default=None, metadata=config(field_name="description")
    )
    keywords: Optional[str] = field(
        default=None, metadata=config(field_name="keywords")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidRiskScore:
    """APIVoidRiskScore."""

    result: Optional[int] = field(default=None, metadata=config(field_name="result"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidAnonymity:
    """APIVoidAnonymity."""

    is_proxy: Optional[bool] = field(
        default=None, metadata=config(field_name="is_proxy")
    )
    is_webproxy: Optional[bool] = field(
        default=None, metadata=config(field_name="is_webproxy")
    )
    is_vpn: Optional[bool] = field(default=None, metadata=config(field_name="is_vpn"))
    is_hosting: Optional[bool] = field(
        default=None, metadata=config(field_name="is_hosting")
    )
    is_tor: Optional[bool] = field(default=None, metadata=config(field_name="is_tor"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidInformation:
    """APIVoidInformation."""

    reverse_dns: Optional[str] = field(
        default=None, metadata=config(field_name="reverse_dns")
    )
    continent_code: Optional[str] = field(
        default=None, metadata=config(field_name="continent_code")
    )
    continent_name: Optional[str] = field(
        default=None, metadata=config(field_name="continent_name")
    )
    country_code: Optional[str] = field(
        default=None, metadata=config(field_name="country_code")
    )
    country_name: Optional[str] = field(
        default=None, metadata=config(field_name="country_name")
    )
    country_currency: Optional[str] = field(
        default=None, metadata=config(field_name="country_currency")
    )
    country_calling_code: Optional[str] = field(
        default=None, metadata=config(field_name="country_calling_code")
    )
    region_name: Optional[str] = field(
        default=None, metadata=config(field_name="region_name")
    )
    city_name: Optional[str] = field(
        default=None, metadata=config(field_name="city_name")
    )
    latitude: Optional[float] = field(
        default=None, metadata=config(field_name="latitude")
    )
    longitude: Optional[float] = field(
        default=None, metadata=config(field_name="longitude")
    )
    isp: Optional[str] = field(default=None, metadata=config(field_name="isp"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidEngine:
    """APIVoidEngine."""

    engine: Optional[str] = field(default=None, metadata=config(field_name="engine"))
    detected: Optional[bool] = field(
        default=None, metadata=config(field_name="detected")
    )
    confidence: Optional[str] = field(
        default=None, metadata=config(field_name="confidence")
    )
    reference: Optional[str] = field(
        default=None, metadata=config(field_name="reference")
    )
    elapsed: Optional[str] = field(default=None, metadata=config(field_name="elapsed"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIndicator:
    """ThreatContextIndicator."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    indicator: Optional[str] = field(
        default=None, metadata=config(field_name="indicator")
    )
    created_at: Optional[str] = field(
        default=None, metadata=config(field_name="createdAt")
    )
    error: Optional[str] = field(default=None, metadata=config(field_name="error"))
    indicator_type: Optional[Union[ThreatContextIndicatorType, TaegisEnum]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(ThreatContextIndicatorType, x),
            field_name="indicatorType",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class CacheOptions:
    """CacheOptions."""

    acceptable_ttl_minutes: Optional[int] = field(
        default=None, metadata=config(field_name="acceptable_ttl_minutes")
    )
    try_cache_how: Optional[Union[CacheStyle, TaegisEnum]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(CacheStyle, x),
            field_name="try_cache_how",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIntelixCreateFileSubmissions:
    """ThreatContextIntelixCreateFileSubmissions."""

    endpoint_id: Optional[str] = field(
        default=None, metadata=config(field_name="endpointId")
    )
    path: Optional[str] = field(default=None, metadata=config(field_name="path"))
    analysis_type: Optional[
        List[Union[ThreatContextIntelixAnalysisType, TaegisEnum]]
    ] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(ThreatContextIntelixAnalysisType, x),
            field_name="analysisType",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIntelixCreateFileSubmissionsInput:
    """ThreatContextIntelixCreateFileSubmissionsInput."""

    sha256: Optional[str] = field(default=None, metadata=config(field_name="sha256"))
    create_file_submissions: Optional[ThreatContextIntelixCreateFileSubmissions] = (
        field(default=None, metadata=config(field_name="createFileSubmissions"))
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalPublicKey:
    """VirusTotalPublicKey."""

    algorithm: Optional[str] = field(
        default=None, metadata=config(field_name="algorithm")
    )
    rsa: Optional[VirusTotalRsa] = field(
        default=None, metadata=config(field_name="rsa")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalLastAnalysisResults:
    """VirusTotalLastAnalysisResults."""

    detections: Optional[List[VirusTotalEngine]] = field(
        default=None, metadata=config(field_name="Detections")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalLastFileAnalysisResults:
    """VirusTotalLastFileAnalysisResults."""

    detections: Optional[List[VirusTotalFileEngine]] = field(
        default=None, metadata=config(field_name="Detections")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class BigBirdGeo:
    """BigBirdGeo."""

    country: Optional[str] = field(default=None, metadata=config(field_name="country"))
    country_iso2: Optional[str] = field(
        default=None, metadata=config(field_name="country_iso2")
    )
    country_iso3: Optional[str] = field(
        default=None, metadata=config(field_name="country_iso3")
    )
    city: Optional[str] = field(default=None, metadata=config(field_name="city"))
    location: Optional[BigBirdLocation] = field(
        default=None, metadata=config(field_name="location")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidDNSRecordHolder:
    """APIVoidDNSRecordHolder."""

    records: Optional[List[APIVoidDNSRecord]] = field(
        default=None, metadata=config(field_name="records")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidURLEngines:
    """APIVoidURLEngines."""

    detections: Optional[int] = field(
        default=None, metadata=config(field_name="detections")
    )
    engines: Optional[List[APIVoidURLEngine]] = field(
        default=None, metadata=config(field_name="engines")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidBlocklists:
    """APIVoidBlocklists."""

    num_detections: Optional[int] = field(
        default=None, metadata=config(field_name="num_detections")
    )
    engines_count: Optional[int] = field(
        default=None, metadata=config(field_name="engines_count")
    )
    detection_rate: Optional[str] = field(
        default=None, metadata=config(field_name="detection_rate")
    )
    scantime: Optional[str] = field(
        default=None, metadata=config(field_name="scantime")
    )
    engines: Optional[List[APIVoidEngine]] = field(
        default=None, metadata=config(field_name="engines")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class RiskyIndicatorArguments:
    """RiskyIndicatorArguments."""

    page: Optional[int] = field(default=None, metadata=config(field_name="page"))
    per_page: Optional[int] = field(default=None, metadata=config(field_name="perPage"))
    order_by: Optional[Union[OrderByOptions, TaegisEnum]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(OrderByOptions, x),
            field_name="orderBy",
        ),
    )
    indicator_type: Optional[Union[ThreatContextIndicatorType, TaegisEnum]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(ThreatContextIndicatorType, x),
            field_name="indicatorType",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIntelixReportInput:
    """ThreatContextIntelixReportInput."""

    sha256: Optional[str] = field(default=None, metadata=config(field_name="sha256"))
    analysis_type: Optional[Union[ThreatContextIntelixAnalysisType, TaegisEnum]] = (
        field(
            default=None,
            metadata=config(
                encoder=encode_enum,
                decoder=lambda x: decode_enum(ThreatContextIntelixAnalysisType, x),
                field_name="analysisType",
            ),
        )
    )
    report_format: Optional[Union[ThreatContextIntelixReportFormat, TaegisEnum]] = (
        field(
            default=None,
            metadata=config(
                encoder=encode_enum,
                decoder=lambda x: decode_enum(ThreatContextIntelixReportFormat, x),
                field_name="reportFormat",
            ),
        )
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIntelixFileSubmissions:
    """ThreatContextIntelixFileSubmissions."""

    submission_id: Optional[str] = field(
        default=None, metadata=config(field_name="submissionId")
    )
    endpoint_id: Optional[str] = field(
        default=None, metadata=config(field_name="endpointId")
    )
    sha256: Optional[str] = field(default=None, metadata=config(field_name="sha256"))
    submission_type: Optional[
        Union[ThreatContextIntelixFileSubmissionType, TaegisEnum]
    ] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(ThreatContextIntelixFileSubmissionType, x),
            field_name="submissionType",
        ),
    )
    status: Optional[Union[ThreatContextIntelixFileAnalysisStatus, TaegisEnum]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(ThreatContextIntelixFileAnalysisStatus, x),
            field_name="status",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalExtensions:
    """VirusTotalExtensions."""

    subject_key_identifier: Optional[str] = field(
        default=None, metadata=config(field_name="subject_key_identifier")
    )
    ca: Optional[bool] = field(default=None, metadata=config(field_name="CA"))
    key_usage: Optional[List[str]] = field(
        default=None, metadata=config(field_name="key_usage")
    )
    crl_distribution_points: Optional[List[str]] = field(
        default=None, metadata=config(field_name="crl_distribution_points")
    )
    subject_alternative_name: Optional[List[str]] = field(
        default=None, metadata=config(field_name="subject_alternative_name")
    )
    tags: Optional[List[str]] = field(default=None, metadata=config(field_name="tags"))
    extended_key_usage: Optional[List[str]] = field(
        default=None, metadata=config(field_name="extended_key_usage")
    )
    certificate_policies: Optional[List[str]] = field(
        default=None, metadata=config(field_name="certificate_policies")
    )
    ca_information_access: Optional[VirusTotalCaInformationAccess] = field(
        default=None, metadata=config(field_name="ca_information_access")
    )
    authority_key_identifier: Optional[VirusTotalAuthorityKeyIdentifier] = field(
        default=None, metadata=config(field_name="authority_key_identifier")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalSandboxVerdicts:
    """VirusTotalSandboxVerdicts."""

    osx_sandbox: Optional[VirusTotalOsxSandbox] = field(
        default=None, metadata=config(field_name="OSXSandbox")
    )
    lastline: Optional[VirusTotalLastline] = field(
        default=None, metadata=config(field_name="Lastline")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalPopularThreatClassification:
    """VirusTotalPopularThreatClassification."""

    suggested_threat_label: Optional[str] = field(
        default=None, metadata=config(field_name="suggested_threat_label")
    )
    popular_threat_name: Optional[List[VirusTotalPopularThreatName]] = field(
        default=None, metadata=config(field_name="popular_threat_name")
    )
    popular_threat_category: Optional[List[VirusTotalPopularThreatCategory]] = field(
        default=None, metadata=config(field_name="popular_threat_category")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class BigBirdDomainReport:
    """BigBirdDomainReport."""

    domain_context: Optional[BigBirdDomainContext] = field(
        default=None, metadata=config(field_name="domain_context")
    )
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class BigBirdFileReport:
    """BigBirdFileReport."""

    file_context: Optional[BigBirdFileContext] = field(
        default=None, metadata=config(field_name="file_context")
    )
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidDNSRecords:
    """APIVoidDNSRecords."""

    ns: Optional[APIVoidDNSRecordHolder] = field(
        default=None, metadata=config(field_name="ns")
    )
    mx: Optional[APIVoidDNSRecordHolder] = field(
        default=None, metadata=config(field_name="mx")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalPopularityRanks:
    """VirusTotalPopularityRanks."""

    cisco_umbrella: Optional[VirusTotalCiscoUmbrella] = field(
        default=None, metadata=config(field_name="CiscoUmbrella")
    )
    alexa: Optional[VirusTotalAlexa] = field(
        default=None, metadata=config(field_name="Alexa")
    )
    statvoo: Optional[VirusTotalStatvoo] = field(
        default=None, metadata=config(field_name="Statvoo")
    )
    majestic: Optional[VirusTotalMajestic] = field(
        default=None, metadata=config(field_name="Majestic")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class BigBirdIPReport:
    """BigBirdIPReport."""

    ip_context: Optional[BigBirdIPContext] = field(
        default=None, metadata=config(field_name="ip_context")
    )
    asn: Optional[BigBirdAsn] = field(default=None, metadata=config(field_name="asn"))
    geo: Optional[BigBirdGeo] = field(default=None, metadata=config(field_name="geo"))
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidReport:
    """APIVoidReport."""

    ip: Optional[str] = field(default=None, metadata=config(field_name="ip"))
    risk_score: Optional[APIVoidRiskScore] = field(
        default=None, metadata=config(field_name="risk_score")
    )
    anonymity: Optional[APIVoidAnonymity] = field(
        default=None, metadata=config(field_name="anonymity")
    )
    information: Optional[APIVoidInformation] = field(
        default=None, metadata=config(field_name="information")
    )
    blocklists: Optional[APIVoidBlocklists] = field(
        default=None, metadata=config(field_name="blocklists")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalLastHttpsCertificate:
    """VirusTotalLastHttpsCertificate."""

    thumbprint_sha256: Optional[str] = field(
        default=None, metadata=config(field_name="thumbprint_sha256")
    )
    signature_algorithm: Optional[str] = field(
        default=None, metadata=config(field_name="signature_algorithm")
    )
    version: Optional[str] = field(default=None, metadata=config(field_name="version"))
    serial_number: Optional[str] = field(
        default=None, metadata=config(field_name="serial_number")
    )
    thumbprint: Optional[str] = field(
        default=None, metadata=config(field_name="thumbprint")
    )
    size: Optional[int] = field(default=None, metadata=config(field_name="size"))
    tags: Optional[List[str]] = field(default=None, metadata=config(field_name="tags"))
    issuer: Optional[VirusTotalCertIssuer] = field(
        default=None, metadata=config(field_name="issuer")
    )
    cert_signature: Optional[VirusTotalCertSignature] = field(
        default=None, metadata=config(field_name="cert_signature")
    )
    extensions: Optional[VirusTotalExtensions] = field(
        default=None, metadata=config(field_name="extensions")
    )
    validity: Optional[VirusTotalValidity] = field(
        default=None, metadata=config(field_name="validity")
    )
    subject: Optional[VirusTotalSubject] = field(
        default=None, metadata=config(field_name="subject")
    )
    public_key: Optional[VirusTotalPublicKey] = field(
        default=None, metadata=config(field_name="public_key")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidDomainReport:
    """APIVoidDomainReport."""

    host: Optional[str] = field(default=None, metadata=config(field_name="host"))
    alexa_top_10k: Optional[bool] = field(
        default=None, metadata=config(field_name="alexa_top_10k")
    )
    domain_length: Optional[int] = field(
        default=None, metadata=config(field_name="domain_length")
    )
    most_abused_tld: Optional[bool] = field(
        default=None, metadata=config(field_name="most_abused_tld")
    )
    alexa_top_100k: Optional[bool] = field(
        default=None, metadata=config(field_name="alexa_top_100k")
    )
    alexa_top_250k: Optional[bool] = field(
        default=None, metadata=config(field_name="alexa_top_250k")
    )
    risk_score: Optional[APIVoidRiskScore] = field(
        default=None, metadata=config(field_name="risk_score")
    )
    category: Optional[APIVoidCategory] = field(
        default=None, metadata=config(field_name="category")
    )
    server: Optional[APIVoidServer] = field(
        default=None, metadata=config(field_name="server")
    )
    blocklists: Optional[APIVoidBlocklists] = field(
        default=None, metadata=config(field_name="blocklists")
    )
    domain_security_checks: Optional[APIVoidDomainSecurityChecks] = field(
        default=None, metadata=config(field_name="domain_security_checks")
    )
    domain_parts: Optional[APIVoidDomainParts] = field(
        default=None, metadata=config(field_name="domain_parts")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalDomainAttributes:
    """VirusTotalDomainAttributes."""

    jarm: Optional[str] = field(default=None, metadata=config(field_name="jarm"))
    whois: Optional[str] = field(default=None, metadata=config(field_name="whois"))
    last_https_certificate_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_https_certificate_date")
    )
    last_dns_records_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_dns_records_date")
    )
    creation_date: Optional[int] = field(
        default=None, metadata=config(field_name="creation_date")
    )
    whois_date: Optional[int] = field(
        default=None, metadata=config(field_name="whois_date")
    )
    reputation: Optional[int] = field(
        default=None, metadata=config(field_name="reputation")
    )
    registrar: Optional[str] = field(
        default=None, metadata=config(field_name="registrar")
    )
    last_update_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_update_date")
    )
    last_modification_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_modification_date")
    )
    tags: Optional[List[str]] = field(default=None, metadata=config(field_name="tags"))
    total_votes: Optional[VirusTotalTotalVotes] = field(
        default=None, metadata=config(field_name="total_votes")
    )
    categories: Optional[List[KeyValuePair]] = field(
        default=None, metadata=config(field_name="categories")
    )
    last_https_certificate: Optional[VirusTotalLastHttpsCertificate] = field(
        default=None, metadata=config(field_name="last_https_certificate")
    )
    last_analysis_results: Optional[VirusTotalLastAnalysisResults] = field(
        default=None, metadata=config(field_name="last_analysis_results")
    )
    last_analysis_stats: Optional[VirusTotalLastAnalysisStats] = field(
        default=None, metadata=config(field_name="last_analysis_stats")
    )
    popularity_ranks: Optional[VirusTotalPopularityRanks] = field(
        default=None, metadata=config(field_name="popularity_ranks")
    )
    last_dns_records: Optional[List[VirusTotalLastDnsRecords]] = field(
        default=None, metadata=config(field_name="last_dns_records")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalURLAttributes:
    """VirusTotalURLAttributes."""

    url: Optional[str] = field(default=None, metadata=config(field_name="url"))
    last_http_response_content_sha256: Optional[str] = field(
        default=None, metadata=config(field_name="last_http_response_content_sha256")
    )
    last_http_response_code: Optional[int] = field(
        default=None, metadata=config(field_name="last_http_response_code")
    )
    last_final_url: Optional[str] = field(
        default=None, metadata=config(field_name="last_final_url")
    )
    redirection_chain: Optional[List[str]] = field(
        default=None, metadata=config(field_name="redirection_chain")
    )
    last_http_response_content_length: Optional[int] = field(
        default=None, metadata=config(field_name="last_http_response_content_length")
    )
    last_analysis_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_analysis_date")
    )
    tags: Optional[List[str]] = field(default=None, metadata=config(field_name="tags"))
    last_submission_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_submission_date")
    )
    outgoing_links: Optional[List[str]] = field(
        default=None, metadata=config(field_name="outgoing_links")
    )
    reputation: Optional[int] = field(
        default=None, metadata=config(field_name="reputation")
    )
    last_modification_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_modification_date")
    )
    title: Optional[str] = field(default=None, metadata=config(field_name="title"))
    times_submitted: Optional[int] = field(
        default=None, metadata=config(field_name="times_submitted")
    )
    first_submission_date: Optional[int] = field(
        default=None, metadata=config(field_name="first_submission_date")
    )
    html_meta: Optional[List[KeyValuePair]] = field(
        default=None, metadata=config(field_name="html_meta")
    )
    last_analysis_results: Optional[VirusTotalLastAnalysisResults] = field(
        default=None, metadata=config(field_name="last_analysis_results")
    )
    last_analysis_stats: Optional[VirusTotalLastAnalysisStats] = field(
        default=None, metadata=config(field_name="last_analysis_stats")
    )
    last_http_response_headers: Optional[List[KeyValuePair]] = field(
        default=None, metadata=config(field_name="last_http_response_headers")
    )
    last_http_response_cookies: Optional[List[KeyValuePair]] = field(
        default=None, metadata=config(field_name="last_http_response_cookies")
    )
    categories: Optional[List[KeyValuePair]] = field(
        default=None, metadata=config(field_name="categories")
    )
    total_votes: Optional[VirusTotalTotalVotes] = field(
        default=None, metadata=config(field_name="total_votes")
    )
    favicon: Optional[List[VirusTotalFavicon]] = field(
        default=None, metadata=config(field_name="favicon")
    )
    trackers: Optional[List[VirusTotalURLTracker]] = field(
        default=None, metadata=config(field_name="trackers")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalFileAttributes:
    """VirusTotalFileAttributes."""

    type_description: Optional[str] = field(
        default=None, metadata=config(field_name="type_description")
    )
    tlsh: Optional[str] = field(default=None, metadata=config(field_name="tlsh"))
    antiy_info: Optional[str] = field(
        default=None, metadata=config(field_name="antiy_info")
    )
    last_modification_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_modification_date")
    )
    type_tag: Optional[str] = field(
        default=None, metadata=config(field_name="type_tag")
    )
    times_submitted: Optional[int] = field(
        default=None, metadata=config(field_name="times_submitted")
    )
    size: Optional[int] = field(default=None, metadata=config(field_name="size"))
    last_submission_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_submission_date")
    )
    meaningful_name: Optional[str] = field(
        default=None, metadata=config(field_name="meaningful_name")
    )
    sha256: Optional[str] = field(default=None, metadata=config(field_name="sha256"))
    type_extension: Optional[str] = field(
        default=None, metadata=config(field_name="type_extension")
    )
    last_analysis_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_analysis_date")
    )
    unique_sources: Optional[int] = field(
        default=None, metadata=config(field_name="unique_sources")
    )
    first_submission_date: Optional[int] = field(
        default=None, metadata=config(field_name="first_submission_date")
    )
    ssdeep: Optional[str] = field(default=None, metadata=config(field_name="ssdeep"))
    md5: Optional[str] = field(default=None, metadata=config(field_name="md5"))
    sha1: Optional[str] = field(default=None, metadata=config(field_name="sha1"))
    magic: Optional[str] = field(default=None, metadata=config(field_name="magic"))
    reputation: Optional[int] = field(
        default=None, metadata=config(field_name="reputation")
    )
    first_seen_itw_date: Optional[int] = field(
        default=None, metadata=config(field_name="first_seen_itw_date")
    )
    tags: Optional[List[str]] = field(default=None, metadata=config(field_name="tags"))
    names: Optional[List[str]] = field(
        default=None, metadata=config(field_name="names")
    )
    capabilities_tags: Optional[List[str]] = field(
        default=None, metadata=config(field_name="capabilities_tags")
    )
    last_analysis_results: Optional[VirusTotalLastFileAnalysisResults] = field(
        default=None, metadata=config(field_name="last_analysis_results")
    )
    last_analysis_stats: Optional[VirusTotalLastFileAnalysisStats] = field(
        default=None, metadata=config(field_name="last_analysis_stats")
    )
    autostart_locations: Optional[List[VirusTotalAutostartLocations]] = field(
        default=None, metadata=config(field_name="autostart_locations")
    )
    sandbox_verdicts: Optional[VirusTotalSandboxVerdicts] = field(
        default=None, metadata=config(field_name="sandbox_verdicts")
    )
    known_distributors: Optional[VirusTotalKnownDistributors] = field(
        default=None, metadata=config(field_name="known_distributors")
    )
    popular_threat_classification: Optional[VirusTotalPopularThreatClassification] = (
        field(default=None, metadata=config(field_name="popular_threat_classification"))
    )
    total_votes: Optional[VirusTotalTotalVotes] = field(
        default=None, metadata=config(field_name="total_votes")
    )
    crowdsourced_yara_results: Optional[List[VirusTotalCrowdsourcedYaraResults]] = (
        field(default=None, metadata=config(field_name="crowdsourced_yara_results"))
    )
    trid: Optional[List[Trid]] = field(default=None, metadata=config(field_name="trid"))
    exiftool: Optional[VirusTotalExiftool] = field(
        default=None, metadata=config(field_name="exiftool")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidURLReport:
    """APIVoidURLReport."""

    dns_records: Optional[APIVoidDNSRecords] = field(
        default=None, metadata=config(field_name="dns_records")
    )
    domain_blacklist: Optional[APIVoidURLEngines] = field(
        default=None, metadata=config(field_name="domain_blacklist")
    )
    file_type: Optional[APIVoidFileType] = field(
        default=None, metadata=config(field_name="file_type")
    )
    geo_location: Optional[APIVoidGeoLocation] = field(
        default=None, metadata=config(field_name="geo_location")
    )
    html_forms: Optional[APIVoidHTMLForms] = field(
        default=None, metadata=config(field_name="html_forms")
    )
    redirection: Optional[APIVoidRedirection] = field(
        default=None, metadata=config(field_name="redirection")
    )
    response_headers: Optional[List[KeyValuePair]] = field(
        default=None, metadata=config(field_name="response_headers")
    )
    risk_score: Optional[APIVoidRiskScore] = field(
        default=None, metadata=config(field_name="risk_score")
    )
    url_security_checks: Optional[APIVoidURLSecurityChecks] = field(
        default=None, metadata=config(field_name="url_security_checks")
    )
    server_details: Optional[APIVoidServerDetails] = field(
        default=None, metadata=config(field_name="server_details")
    )
    site_category: Optional[APIVoidSiteCategory] = field(
        default=None, metadata=config(field_name="site_category")
    )
    url_parts: Optional[APIVoidURLParts] = field(
        default=None, metadata=config(field_name="url_parts")
    )
    web_page: Optional[APIVoidWebPage] = field(
        default=None, metadata=config(field_name="web_page")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIntelixFileSubmissionsResponse:
    """ThreatContextIntelixFileSubmissionsResponse."""

    error: Optional[str] = field(default=None, metadata=config(field_name="error"))
    file_submissions: Optional[ThreatContextIntelixFileSubmissions] = field(
        default=None, metadata=config(field_name="fileSubmissions")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIntelixGetLatestFileSubmissionResponse:
    """ThreatContextIntelixGetLatestFileSubmissionResponse."""

    error: Optional[str] = field(default=None, metadata=config(field_name="error"))
    file_submission: Optional[ThreatContextIntelixFileSubmissions] = field(
        default=None, metadata=config(field_name="fileSubmission")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidDomainData:
    """APIVoidDomainData."""

    report: Optional[APIVoidDomainReport] = field(
        default=None, metadata=config(field_name="report")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidURLData:
    """APIVoidURLData."""

    report: Optional[APIVoidURLReport] = field(
        default=None, metadata=config(field_name="report")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidData:
    """APIVoidData."""

    report: Optional[APIVoidReport] = field(
        default=None, metadata=config(field_name="report")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalDomainData:
    """VirusTotalDomainData."""

    type: Optional[str] = field(default=None, metadata=config(field_name="type"))
    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    no_results: Optional[bool] = field(
        default=None, metadata=config(field_name="noResults")
    )
    links: Optional[VirusTotalLinks] = field(
        default=None, metadata=config(field_name="links")
    )
    attributes: Optional[VirusTotalDomainAttributes] = field(
        default=None, metadata=config(field_name="attributes")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalDomainReport:
    """VirusTotalDomainReport."""

    data: Optional[VirusTotalDomainData] = field(
        default=None, metadata=config(field_name="data")
    )
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalURLData:
    """VirusTotalURLData."""

    type: Optional[str] = field(default=None, metadata=config(field_name="type"))
    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    no_results: Optional[bool] = field(
        default=None, metadata=config(field_name="noResults")
    )
    links: Optional[VirusTotalLinks] = field(
        default=None, metadata=config(field_name="links")
    )
    attributes: Optional[VirusTotalURLAttributes] = field(
        default=None, metadata=config(field_name="attributes")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalURLReport:
    """VirusTotalURLReport."""

    data: Optional[VirusTotalURLData] = field(
        default=None, metadata=config(field_name="data")
    )
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalFileData:
    """VirusTotalFileData."""

    type: Optional[str] = field(default=None, metadata=config(field_name="type"))
    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    no_results: Optional[bool] = field(
        default=None, metadata=config(field_name="noResults")
    )
    links: Optional[VirusTotalLinks] = field(
        default=None, metadata=config(field_name="links")
    )
    attributes: Optional[VirusTotalFileAttributes] = field(
        default=None, metadata=config(field_name="attributes")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalFileReport:
    """VirusTotalFileReport."""

    data: Optional[VirusTotalFileData] = field(
        default=None, metadata=config(field_name="data")
    )
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidDomain:
    """APIVoidDomain."""

    credits_remained: Optional[float] = field(
        default=None,
        metadata=config(
            metadata={
                "deprecated": True,
                "deprecation_reason": "use apiVoidStats query",
            },
            field_name="credits_remained",
        ),
    )
    estimated_queries: Optional[str] = field(
        default=None,
        metadata=config(
            metadata={
                "deprecated": True,
                "deprecation_reason": "use apiVoidStats query",
            },
            field_name="estimated_queries",
        ),
    )
    elapsed_time: Optional[str] = field(
        default=None, metadata=config(field_name="elapsed_time")
    )
    success: Optional[bool] = field(default=None, metadata=config(field_name="success"))
    data: Optional[APIVoidDomainData] = field(
        default=None, metadata=config(field_name="data")
    )
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidURL:
    """APIVoidURL."""

    credits_remained: Optional[float] = field(
        default=None,
        metadata=config(
            metadata={
                "deprecated": True,
                "deprecation_reason": "use apiVoidStats query",
            },
            field_name="credits_remained",
        ),
    )
    estimated_queries: Optional[str] = field(
        default=None,
        metadata=config(
            metadata={
                "deprecated": True,
                "deprecation_reason": "use apiVoidStats query",
            },
            field_name="estimated_queries",
        ),
    )
    elapsed_time: Optional[str] = field(
        default=None, metadata=config(field_name="elapsed_time")
    )
    success: Optional[bool] = field(default=None, metadata=config(field_name="success"))
    data: Optional[APIVoidURLData] = field(
        default=None, metadata=config(field_name="data")
    )
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class APIVoidIP:
    """APIVoidIP."""

    credits_remained: Optional[float] = field(
        default=None,
        metadata=config(
            metadata={
                "deprecated": True,
                "deprecation_reason": "use apiVoidStats query",
            },
            field_name="credits_remained",
        ),
    )
    estimated_queries: Optional[str] = field(
        default=None,
        metadata=config(
            metadata={
                "deprecated": True,
                "deprecation_reason": "use apiVoidStats query",
            },
            field_name="estimated_queries",
        ),
    )
    elapsed_time: Optional[str] = field(
        default=None, metadata=config(field_name="elapsed_time")
    )
    success: Optional[bool] = field(default=None, metadata=config(field_name="success"))
    data: Optional[APIVoidData] = field(
        default=None, metadata=config(field_name="data")
    )
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextFileInfo:
    """ThreatContextFileInfo."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    indicator: Optional[str] = field(
        default=None, metadata=config(field_name="indicator")
    )
    error: Optional[str] = field(default=None, metadata=config(field_name="error"))
    virustotal_results: Optional[VirusTotalFileReport] = field(
        default=None, metadata=config(field_name="virustotal_results")
    )
    bigbird_results: Optional[BigBirdFileReport] = field(
        default=None, metadata=config(field_name="bigbird_results")
    )
    reputation_stats: Optional[ReputationStats] = field(
        default=None, metadata=config(field_name="reputation_stats")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextURLInfo:
    """ThreatContextURLInfo."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    indicator: Optional[str] = field(
        default=None, metadata=config(field_name="indicator")
    )
    error: Optional[str] = field(default=None, metadata=config(field_name="error"))
    apivoid_results: Optional[APIVoidURL] = field(
        default=None, metadata=config(field_name="apivoid_results")
    )
    virustotal_results: Optional[VirusTotalURLReport] = field(
        default=None, metadata=config(field_name="virustotal_results")
    )
    reputation_stats: Optional[ReputationStats] = field(
        default=None, metadata=config(field_name="reputation_stats")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextDomainInfo:
    """ThreatContextDomainInfo."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    indicator: Optional[str] = field(
        default=None, metadata=config(field_name="indicator")
    )
    error: Optional[str] = field(default=None, metadata=config(field_name="error"))
    apivoid_results: Optional[APIVoidDomain] = field(
        default=None, metadata=config(field_name="apivoid_results")
    )
    virustotal_results: Optional[VirusTotalDomainReport] = field(
        default=None, metadata=config(field_name="virustotal_results")
    )
    bigbird_results: Optional[BigBirdDomainReport] = field(
        default=None, metadata=config(field_name="bigbird_results")
    )
    reputation_stats: Optional[ReputationStats] = field(
        default=None, metadata=config(field_name="reputation_stats")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalIPAttributes:
    """VirusTotalIPAttributes."""

    network: Optional[str] = field(default=None, metadata=config(field_name="network"))
    as_owner: Optional[str] = field(
        default=None, metadata=config(field_name="as_owner")
    )
    whois_date: Optional[int] = field(
        default=None, metadata=config(field_name="whois_date")
    )
    reputation: Optional[int] = field(
        default=None, metadata=config(field_name="reputation")
    )
    last_modification_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_modification_date")
    )
    asn: Optional[int] = field(default=None, metadata=config(field_name="asn"))
    whois: Optional[str] = field(default=None, metadata=config(field_name="whois"))
    last_https_certificate_date: Optional[int] = field(
        default=None, metadata=config(field_name="last_https_certificate_date")
    )
    tags: Optional[List[str]] = field(default=None, metadata=config(field_name="tags"))
    total_votes: Optional[VirusTotalTotalVotes] = field(
        default=None, metadata=config(field_name="total_votes")
    )
    last_analysis_results: Optional[VirusTotalLastAnalysisResults] = field(
        default=None, metadata=config(field_name="last_analysis_results")
    )
    last_analysis_stats: Optional[VirusTotalLastAnalysisStats] = field(
        default=None, metadata=config(field_name="last_analysis_stats")
    )
    last_https_certificate: Optional[VirusTotalLastHttpsCertificate] = field(
        default=None, metadata=config(field_name="last_https_certificate")
    )
    crowdsourced_context: Optional[List[VirusTotalCrowdsourcedContext]] = field(
        default=None, metadata=config(field_name="crowdsourced_context")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalIPData:
    """VirusTotalIPData."""

    type: Optional[str] = field(default=None, metadata=config(field_name="type"))
    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    no_results: Optional[bool] = field(
        default=None, metadata=config(field_name="noResults")
    )
    links: Optional[VirusTotalLinks] = field(
        default=None, metadata=config(field_name="links")
    )
    attributes: Optional[VirusTotalIPAttributes] = field(
        default=None, metadata=config(field_name="attributes")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class VirusTotalIPReport:
    """VirusTotalIPReport."""

    data: Optional[VirusTotalIPData] = field(
        default=None, metadata=config(field_name="data")
    )
    cache_results: Optional[CacheResults] = field(
        default=None, metadata=config(field_name="cache_results")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ThreatContextIPInfo:
    """ThreatContextIPInfo."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    indicator: Optional[str] = field(
        default=None, metadata=config(field_name="indicator")
    )
    error: Optional[str] = field(default=None, metadata=config(field_name="error"))
    apivoid_results: Optional[APIVoidIP] = field(
        default=None, metadata=config(field_name="apivoid_results")
    )
    virustotal_results: Optional[VirusTotalIPReport] = field(
        default=None, metadata=config(field_name="virustotal_results")
    )
    bigbird_results: Optional[BigBirdIPReport] = field(
        default=None, metadata=config(field_name="bigbird_results")
    )
    reputation_stats: Optional[ReputationStats] = field(
        default=None, metadata=config(field_name="reputation_stats")
    )


Results = Union[
    ThreatContextDomainInfo,
    ThreatContextIPInfo,
    ThreatContextFileInfo,
    ThreatContextURLInfo,
]
