"""EscalationPolicies Types and Enums."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code

# Autogenerated
# DO NOT MODIFY

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Union

from dataclasses_json import config, dataclass_json

from taegis_sdk_python._consts import TaegisEnum
from taegis_sdk_python.utils import decode_enum, encode_enum, parse_union_result


class ContactSource(str, Enum):
    """ContactSource."""

    REGISTERED = "REGISTERED"
    EXTERNAL = "EXTERNAL"


class DaysOfWeek(str, Enum):
    """DaysOfWeek."""

    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class EscalationPoliciesArguments:
    """EscalationPoliciesArguments."""

    cql: Optional[str] = field(default=None, metadata=config(field_name="cql"))
    page: Optional[int] = field(default=None, metadata=config(field_name="page"))
    per_page: Optional[int] = field(default=None, metadata=config(field_name="perPage"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class EscalationPolicyArguments:
    """EscalationPolicyArguments."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class DeleteEscalationPolicyInput:
    """DeleteEscalationPolicyInput."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ExternalContact:
    """ExternalContact."""

    primary_phone: Optional[str] = field(
        default=None, metadata=config(field_name="primaryPhone")
    )
    primary_phone_extension: Optional[str] = field(
        default=None, metadata=config(field_name="primaryPhoneExtension")
    )
    secondary_phone: Optional[str] = field(
        default=None, metadata=config(field_name="secondaryPhone")
    )
    secondary_phone_extension: Optional[str] = field(
        default=None, metadata=config(field_name="secondaryPhoneExtension")
    )
    email: Optional[str] = field(default=None, metadata=config(field_name="email"))
    first_name: Optional[str] = field(
        default=None, metadata=config(field_name="firstName")
    )
    last_name: Optional[str] = field(
        default=None, metadata=config(field_name="lastName")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class CreateExternalContactInput:
    """CreateExternalContactInput."""

    primary_phone: Optional[str] = field(
        default=None, metadata=config(field_name="primaryPhone")
    )
    primary_phone_extension: Optional[str] = field(
        default=None, metadata=config(field_name="primaryPhoneExtension")
    )
    secondary_phone: Optional[str] = field(
        default=None, metadata=config(field_name="secondaryPhone")
    )
    secondary_phone_extension: Optional[str] = field(
        default=None, metadata=config(field_name="secondaryPhoneExtension")
    )
    email: Optional[str] = field(default=None, metadata=config(field_name="email"))
    first_name: Optional[str] = field(
        default=None, metadata=config(field_name="firstName")
    )
    last_name: Optional[str] = field(
        default=None, metadata=config(field_name="lastName")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class UpdateExternalContactInput:
    """UpdateExternalContactInput."""

    primary_phone: Optional[str] = field(
        default=None, metadata=config(field_name="primaryPhone")
    )
    primary_phone_extension: Optional[str] = field(
        default=None, metadata=config(field_name="primaryPhoneExtension")
    )
    secondary_phone: Optional[str] = field(
        default=None, metadata=config(field_name="secondaryPhone")
    )
    secondary_phone_extension: Optional[str] = field(
        default=None, metadata=config(field_name="secondaryPhoneExtension")
    )
    email: Optional[str] = field(default=None, metadata=config(field_name="email"))
    first_name: Optional[str] = field(
        default=None, metadata=config(field_name="firstName")
    )
    last_name: Optional[str] = field(
        default=None, metadata=config(field_name="lastName")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ContactMethodOption:
    """ContactMethodOption."""

    name: Optional[str] = field(default=None, metadata=config(field_name="name"))
    title: Optional[str] = field(default=None, metadata=config(field_name="title"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class WalkEscalationPolicyArguments:
    """WalkEscalationPolicyArguments."""

    escalation_policy_id: Optional[str] = field(
        default=None, metadata=config(field_name="escalationPolicyId")
    )
    step_index: Optional[int] = field(
        default=None, metadata=config(field_name="stepIndex")
    )
    resource_type: Optional[str] = field(
        default=None, metadata=config(field_name="resourceType")
    )
    resource_id: Optional[str] = field(
        default=None, metadata=config(field_name="resourceId")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class Subject:
    """Subject."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ContactMethodOptionsArguments:
    """ContactMethodOptionsArguments."""

    source: Optional[Union[ContactSource, TaegisEnum]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(ContactSource, x),
            field_name="source",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ContactMethods:
    """ContactMethods."""

    methods: Optional[List[ContactMethodOption]] = field(
        default=None, metadata=config(field_name="methods")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class CreateEscalationStepInput:
    """CreateEscalationStepInput."""

    description: Optional[str] = field(
        default=None, metadata=config(field_name="description")
    )
    user_id: Optional[str] = field(default=None, metadata=config(field_name="userId"))
    active_from: Optional[str] = field(
        default=None, metadata=config(field_name="activeFrom")
    )
    active_until: Optional[str] = field(
        default=None, metadata=config(field_name="activeUntil")
    )
    contact_methods: Optional[List[str]] = field(
        default=None, metadata=config(field_name="contactMethods")
    )
    filter: Optional[str] = field(default=None, metadata=config(field_name="filter"))
    external_contact: Optional[CreateExternalContactInput] = field(
        default=None, metadata=config(field_name="externalContact")
    )
    active_days: Optional[List[Union[DaysOfWeek, TaegisEnum]]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(DaysOfWeek, x),
            field_name="activeDays",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class UpdateEscalationStepInput:
    """UpdateEscalationStepInput."""

    description: Optional[str] = field(
        default=None, metadata=config(field_name="description")
    )
    user_id: Optional[str] = field(default=None, metadata=config(field_name="userId"))
    active_from: Optional[str] = field(
        default=None, metadata=config(field_name="activeFrom")
    )
    active_until: Optional[str] = field(
        default=None, metadata=config(field_name="activeUntil")
    )
    contact_methods: Optional[List[str]] = field(
        default=None, metadata=config(field_name="contactMethods")
    )
    filter: Optional[str] = field(default=None, metadata=config(field_name="filter"))
    external_contact: Optional[UpdateExternalContactInput] = field(
        default=None, metadata=config(field_name="externalContact")
    )
    active_days: Optional[List[Union[DaysOfWeek, TaegisEnum]]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(DaysOfWeek, x),
            field_name="activeDays",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class EscalationStep:
    """EscalationStep."""

    description: Optional[str] = field(
        default=None, metadata=config(field_name="description")
    )
    user_id: Optional[str] = field(default=None, metadata=config(field_name="userId"))
    active_from: Optional[str] = field(
        default=None, metadata=config(field_name="activeFrom")
    )
    active_until: Optional[str] = field(
        default=None, metadata=config(field_name="activeUntil")
    )
    contact_methods: Optional[List[str]] = field(
        default=None, metadata=config(field_name="contactMethods")
    )
    filter: Optional[str] = field(default=None, metadata=config(field_name="filter"))
    user_subject: Optional[Subject] = field(
        default=None, metadata=config(field_name="userSubject")
    )
    external_contact: Optional[ExternalContact] = field(
        default=None, metadata=config(field_name="externalContact")
    )
    active_days: Optional[List[Union[DaysOfWeek, TaegisEnum]]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(DaysOfWeek, x),
            field_name="activeDays",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class CreateEscalationPolicyInput:
    """CreateEscalationPolicyInput."""

    name: Optional[str] = field(default=None, metadata=config(field_name="name"))
    description: Optional[str] = field(
        default=None, metadata=config(field_name="description")
    )
    delay: Optional[int] = field(default=None, metadata=config(field_name="delay"))
    steps: Optional[List[CreateEscalationStepInput]] = field(
        default=None, metadata=config(field_name="steps")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class UpdateEscalationPolicyInput:
    """UpdateEscalationPolicyInput."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    name: Optional[str] = field(default=None, metadata=config(field_name="name"))
    description: Optional[str] = field(
        default=None, metadata=config(field_name="description")
    )
    delay: Optional[int] = field(default=None, metadata=config(field_name="delay"))
    steps: Optional[List[UpdateEscalationStepInput]] = field(
        default=None, metadata=config(field_name="steps")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class EscalationPolicyStep:
    """EscalationPolicyStep."""

    step_index: Optional[int] = field(
        default=None, metadata=config(field_name="stepIndex")
    )
    step: Optional[EscalationStep] = field(
        default=None, metadata=config(field_name="step")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class EscalationPolicy:
    """EscalationPolicy."""

    id: Optional[str] = field(default=None, metadata=config(field_name="id"))
    name: Optional[str] = field(default=None, metadata=config(field_name="name"))
    description: Optional[str] = field(
        default=None, metadata=config(field_name="description")
    )
    tenant_id: Optional[str] = field(
        default=None, metadata=config(field_name="tenantId")
    )
    created_by_id: Optional[str] = field(
        default=None, metadata=config(field_name="createdById")
    )
    created_at: Optional[str] = field(
        default=None, metadata=config(field_name="createdAt")
    )
    updated_by_id: Optional[str] = field(
        default=None, metadata=config(field_name="updatedById")
    )
    updated_at: Optional[str] = field(
        default=None, metadata=config(field_name="updatedAt")
    )
    delay: Optional[int] = field(default=None, metadata=config(field_name="delay"))
    created_by_subject: Optional[Subject] = field(
        default=None, metadata=config(field_name="createdBySubject")
    )
    updated_by_subject: Optional[Subject] = field(
        default=None, metadata=config(field_name="updatedBySubject")
    )
    steps: Optional[List[EscalationStep]] = field(
        default=None, metadata=config(field_name="steps")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class EscalationPolicies:
    """EscalationPolicies."""

    total_count: Optional[int] = field(
        default=None, metadata=config(field_name="totalCount")
    )
    escalation_policies: Optional[List[EscalationPolicy]] = field(
        default=None, metadata=config(field_name="escalationPolicies")
    )
