"""Audits Subscription."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING


if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.audits import AuditsService

log = logging.getLogger(__name__)


class TaegisSDKAuditsSubscription:
    """Taegis Audits Subscription operations."""

    def __init__(self, service: AuditsService):
        self.service = service
