"""Health Query."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple, Union

from taegis_sdk_python import GraphQLNoRowsInResultSetError
from taegis_sdk_python._consts import TaegisEnum
from taegis_sdk_python.services.health.types import *
from taegis_sdk_python.utils import (
    build_output_string,
    parse_union_result,
    prepare_input,
)

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.health import HealthService

log = logging.getLogger(__name__)


class TaegisSDKHealthQuery:
    """Taegis Health Query operations."""

    def __init__(self, service: HealthService):
        self.service = service

    def ndr_health_last_event(self, device_name: str) -> NDRHealthLastEvents:
        """Query to get event timestamps."""
        endpoint = "ndrHealthLastEvent"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "deviceName": prepare_input(device_name),
            },
            output=build_output_string(
                NDRHealthLastEvents,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NDRHealthLastEvents.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query ndrHealthLastEvent")

    def ndr_health_status(self, device_name: str) -> List[NDRHealthStatus]:
        """Query to get health status of a device."""
        endpoint = "ndrHealthStatus"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "deviceName": prepare_input(device_name),
            },
            output=build_output_string(
                NDRHealthStatus,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NDRHealthStatus.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query ndrHealthStatus")

    def ndr_health_statuses(self) -> List[NDRHealthStatuses]:
        """Query to get list of devices with health status of each device."""
        endpoint = "ndrHealthStatuses"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={},
            output=build_output_string(
                NDRHealthStatuses,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NDRHealthStatuses.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query ndrHealthStatuses")

    def ndr_health_metrics(
        self, ndr_health_metrics_query: NDRHealthMetricsQuery
    ) -> List[NDRHealthMetricsResponse]:
        """Query to get health metrics of a device for the requested type."""
        endpoint = "ndrHealthMetrics"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "ndrHealthMetricsQuery": prepare_input(ndr_health_metrics_query),
            },
            output=build_output_string(
                NDRHealthMetricsResponse,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return NDRHealthMetricsResponse.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query ndrHealthMetrics")
