"""Agent Query."""
# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from taegis_sdk_python import GraphQLNoRowsInResultSetError
from taegis_sdk_python.services.agent.types import *
from taegis_sdk_python.utils import (
    build_output_string,
    prepare_input,
)

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.agent import AgentService

log = logging.getLogger(__name__)


class TaegisSDKAgentQuery:
    """Taegis Agent Query operations."""

    def __init__(self, service: AgentService):
        self.service = service

    def agent_packages(self, args: PackageSearchInput | None = None) -> list[Package]:
        """search for agent packages ."""
        endpoint = "agentPackages"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "args": prepare_input(args),
            },
            output=build_output_string(
                Package,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return Package.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query agentPackages")

    def agent_package_signed_url(
        self, args: PackageDownloadInput | None = None
    ) -> PackageSignedUrl:
        """get agent package via signed url ."""
        endpoint = "agentPackageSignedUrl"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "args": prepare_input(args),
            },
            output=build_output_string(
                PackageSignedUrl,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return PackageSignedUrl.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query agentPackageSignedUrl")

    def agent_package_signed_url_by_id(self, id_: str) -> PackageSignedUrl:
        """get agent package by id via signed url ."""
        endpoint = "agentPackageSignedUrlByID"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "id": prepare_input(id_),
            },
            output=build_output_string(
                PackageSignedUrl,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return PackageSignedUrl.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query agentPackageSignedUrlByID")

    def available_channels(self) -> list[ReleaseChannelsConfig]:
        """get all available channels ."""
        endpoint = "availableChannels"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={},
            output=build_output_string(
                ReleaseChannelsConfig,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return ReleaseChannelsConfig.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query availableChannels")
