"""Search Query."""
# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

from taegis_sdk_python import GraphQLNoRowsInResultSetError
from taegis_sdk_python.services.search.types import *
from taegis_sdk_python.utils import (
    build_output_string,
    prepare_input,
)

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.search import SearchService

log = logging.getLogger(__name__)


class TaegisSDKSearchQuery:
    """Taegis Search Query operations."""

    def __init__(self, service: SearchService):
        self.service = service

    def search(self, urn: str) -> SearchV2:
        """Retrieve search information and its current state."""
        endpoint = "search"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "urn": prepare_input(urn),
            },
            output=build_output_string(
                SearchV2,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return SearchV2.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query search")

    def searches_by_history_id(self, ids: list[str]) -> list[SearchV2]:
        """Retrieve searches via their linked search history service ids."""
        endpoint = "searchesByHistoryId"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "ids": prepare_input(ids),
            },
            output=build_output_string(
                SearchV2,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return SearchV2.schema().load(
                [r or {} for r in result.get(endpoint)], many=True
            )
        raise GraphQLNoRowsInResultSetError("for query searchesByHistoryId")

    def validate_search(self, input_: ValidateSearchInput) -> ValidateSearchResponse:
        """Run validation against a search query input without executing it."""
        endpoint = "validateSearch"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "input": prepare_input(input_),
            },
            output=build_output_string(
                ValidateSearchResponse,
                exclude_deprecated_output=self.service.exclude_deprecated_output,
            ),
        )
        if result.get(endpoint) is not None:
            return ValidateSearchResponse.from_dict(result.get(endpoint))
        raise GraphQLNoRowsInResultSetError("for query validateSearch")

    def query_spec(self, text: str) -> Any:
        """Parse QL text in to structured QuerySpec format."""
        endpoint = "querySpec"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "text": prepare_input(text),
            },
            output="",
        )
        if result.get(endpoint) is not None:
            return result.get(endpoint)
        raise GraphQLNoRowsInResultSetError("for query querySpec")

    def query_text(self, spec: Any) -> str:
        """Generate a canonical QL text representation of a query in structured QuerySpec
        format."""
        endpoint = "queryText"

        result = self.service.execute_query(
            endpoint=endpoint,
            variables={
                "spec": prepare_input(spec),
            },
            output="",
        )
        if result.get(endpoint) is not None:
            return result.get(endpoint)
        raise GraphQLNoRowsInResultSetError("for query queryText")
