"""Search Types and Enums."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code

# Autogenerated
# DO NOT MODIFY

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Union

from dataclasses_json import config, dataclass_json

from taegis_sdk_python._consts import TaegisEnum
from taegis_sdk_python.utils import decode_enum, encode_enum, parse_union_result


class BaseType(str, Enum):
    """BaseType."""

    STRING = "STRING"
    NUMBER = "NUMBER"
    BOOL = "BOOL"
    TIMESTAMP_SECONDS = "TIMESTAMP_SECONDS"
    TIMESTAMP_MILLISECONDS = "TIMESTAMP_MILLISECONDS"
    TIMESTAMP_MICROSECONDS = "TIMESTAMP_MICROSECONDS"
    TIMESTAMP_ISO_8601 = "TIMESTAMP_ISO_8601"
    BYTES = "BYTES"
    ENUM = "ENUM"
    STRING_LIST = "STRING_LIST"
    NUMBER_LIST = "NUMBER_LIST"
    BOOL_LIST = "BOOL_LIST"
    TIMESTAMP_SECONDS_LIST = "TIMESTAMP_SECONDS_LIST"
    TIMESTAMP_MILLISECONDS_LIST = "TIMESTAMP_MILLISECONDS_LIST"
    TIMESTAMP_MICROSECONDS_LIST = "TIMESTAMP_MICROSECONDS_LIST"
    TIMESTAMP_ISO_8601_LIST = "TIMESTAMP_ISO_8601_LIST"
    BYTES_LIST = "BYTES_LIST"
    ENUM_LIST = "ENUM_LIST"
    STRING_MAP = "STRING_MAP"
    NUMBER_MAP = "NUMBER_MAP"
    BOOL_MAP = "BOOL_MAP"
    TIMESTAMP_SECONDS_MAP = "TIMESTAMP_SECONDS_MAP"
    TIMESTAMP_MILLISECONDS_MAP = "TIMESTAMP_MILLISECONDS_MAP"
    TIMESTAMP_MICROSECONDS_MAP = "TIMESTAMP_MICROSECONDS_MAP"
    TIMESTAMP_ISO_8601_MAP = "TIMESTAMP_ISO_8601_MAP"
    BYTES_MAP = "BYTES_MAP"
    ENUM_MAP = "ENUM_MAP"


class LogicalType(str, Enum):
    """LogicalType."""

    COMMAND = "COMMAND"
    HASH = "HASH"
    DOMAIN = "DOMAIN"
    HOST = "HOST"
    IP = "IP"
    LATITUDE = "LATITUDE"
    LONGITUDE = "LONGITUDE"
    MAC = "MAC"
    PATH = "PATH"
    PORT = "PORT"
    RAW = "RAW"
    USER = "USER"
    URL = "URL"
    UUID = "UUID"
    SENSOR_ID = "SENSOR_ID"
    TIMESTAMP = "TIMESTAMP"


class SearchState(str, Enum):
    """SearchState."""

    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    SUCCEEDED = "SUCCEEDED"
    UNTRACKED = "UNTRACKED"
    NOTFOUND = "NOTFOUND"


class QueryHistoryVisibility(str, Enum):
    """QueryHistoryVisibility."""

    NONE = "NONE"
    TENANT = "TENANT"


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ValidateSearchInput:
    """ValidateSearchInput."""

    text: Optional[str] = field(default=None, metadata=config(field_name="text"))
    spec: Optional[Any] = field(default=None, metadata=config(field_name="spec"))
    repository: Optional[str] = field(
        default=None, metadata=config(field_name="repository")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ValidationErrorRange:
    """ValidationErrorRange."""

    start_line: Optional[int] = field(
        default=None, metadata=config(field_name="startLine")
    )
    stop_line: Optional[int] = field(
        default=None, metadata=config(field_name="stopLine")
    )
    start_column: Optional[int] = field(
        default=None, metadata=config(field_name="startColumn")
    )
    stop_column: Optional[int] = field(
        default=None, metadata=config(field_name="stopColumn")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class SearchPartition:
    """SearchPartition."""

    rn: Optional[str] = field(default=None, metadata=config(field_name="rn"))
    history_rn: Optional[str] = field(
        default=None, metadata=config(field_name="historyRN")
    )
    resource_type: Optional[str] = field(
        default=None, metadata=config(field_name="resourceType")
    )
    query_text: Optional[str] = field(
        default=None, metadata=config(field_name="queryText")
    )
    query_spec: Optional[Any] = field(
        default=None, metadata=config(field_name="querySpec")
    )
    create_time: Optional[str] = field(
        default=None, metadata=config(field_name="createTime")
    )
    start_time: Optional[str] = field(
        default=None, metadata=config(field_name="startTime")
    )
    end_time: Optional[str] = field(default=None, metadata=config(field_name="endTime"))
    expire_time: Optional[str] = field(
        default=None, metadata=config(field_name="expireTime")
    )
    errors: Optional[List[str]] = field(
        default=None, metadata=config(field_name="errors")
    )
    created_by: Optional[str] = field(
        default=None, metadata=config(field_name="createdBy")
    )
    state: Optional[Union[SearchState, TaegisEnum]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(SearchState, x),
            field_name="state",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class QueryHistoryInput:
    """QueryHistoryInput."""

    caller_name: Optional[str] = field(
        default=None, metadata=config(field_name="callerName")
    )
    visibility: Optional[Union[QueryHistoryVisibility, TaegisEnum]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(QueryHistoryVisibility, x),
            field_name="visibility",
        ),
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ValidationError:
    """ValidationError."""

    description: Optional[str] = field(
        default=None, metadata=config(field_name="description")
    )
    location: Optional[ValidationErrorRange] = field(
        default=None, metadata=config(field_name="location")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class SearchV2:
    """SearchV2."""

    rn: Optional[str] = field(default=None, metadata=config(field_name="rn"))
    history_rn: Optional[str] = field(
        default=None, metadata=config(field_name="historyRN")
    )
    errors: Optional[List[str]] = field(
        default=None, metadata=config(field_name="errors")
    )
    query_text: Optional[str] = field(
        default=None, metadata=config(field_name="queryText")
    )
    query_spec: Optional[Any] = field(
        default=None, metadata=config(field_name="querySpec")
    )
    create_time: Optional[str] = field(
        default=None, metadata=config(field_name="createTime")
    )
    start_time: Optional[str] = field(
        default=None, metadata=config(field_name="startTime")
    )
    end_time: Optional[str] = field(default=None, metadata=config(field_name="endTime"))
    expire_time: Optional[str] = field(
        default=None, metadata=config(field_name="expireTime")
    )
    metadata: Optional[dict] = field(
        default=None, metadata=config(field_name="metadata")
    )
    state: Optional[Union[SearchState, TaegisEnum]] = field(
        default=None,
        metadata=config(
            encoder=encode_enum,
            decoder=lambda x: decode_enum(SearchState, x),
            field_name="state",
        ),
    )
    search_partitions: Optional[List[SearchPartition]] = field(
        default=None, metadata=config(field_name="searchPartitions")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class ValidateSearchOutput:
    """ValidateSearchOutput."""

    query_text: Optional[str] = field(
        default=None, metadata=config(field_name="queryText")
    )
    query_spec: Optional[Any] = field(
        default=None, metadata=config(field_name="querySpec")
    )
    resolved_types: Optional[List[str]] = field(
        default=None, metadata=config(field_name="resolvedTypes")
    )
    errors: Optional[List[ValidationError]] = field(
        default=None, metadata=config(field_name="errors")
    )
    warnings: Optional[List[ValidationError]] = field(
        default=None, metadata=config(field_name="warnings")
    )


@dataclass_json
@dataclass(order=True, eq=True, frozen=True)
class CreateSearchInput:
    """CreateSearchInput."""

    text: Optional[str] = field(default=None, metadata=config(field_name="text"))
    spec: Optional[Any] = field(default=None, metadata=config(field_name="spec"))
    repository: Optional[str] = field(
        default=None, metadata=config(field_name="repository")
    )
    metadata: Optional[dict] = field(
        default=None, metadata=config(field_name="metadata")
    )
    query_history_input: Optional[QueryHistoryInput] = field(
        default=None, metadata=config(field_name="queryHistoryInput")
    )
