"""EntityContext Subscription."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from taegis_sdk_python.services.entity_context.types import *

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.entity_context import EntityContextService

log = logging.getLogger(__name__)


class TaegisSDKEntityContextSubscription:
    """Taegis Entity_context Subscription operations."""

    def __init__(self, service: EntityContextService):
        self.service = service
