"""DetectorRegistry Mutation."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING


if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.detector_registry import DetectorRegistryService

log = logging.getLogger(__name__)


class TaegisSDKDetectorRegistryMutation:
    """Taegis Detector_registry Mutation operations."""

    def __init__(self, service: DetectorRegistryService):
        self.service = service
