"""DetectorRegistry Subscription."""
# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from taegis_sdk_python.services.detector_registry.types import *

if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.detector_registry import DetectorRegistryService

log = logging.getLogger(__name__)


class TaegisSDKDetectorRegistrySubscription:
    """Taegis Detector_registry Subscription operations."""

    def __init__(self, service: DetectorRegistryService):
        self.service = service
