"""AlertsHistory Mutation."""

# pylint: disable=no-member, unused-argument, too-many-locals, duplicate-code, wildcard-import, unused-wildcard-import, cyclic-import


# Autogenerated
# DO NOT MODIFY

from __future__ import annotations

import logging
from typing import TYPE_CHECKING


if TYPE_CHECKING:  # pragma: no cover
    from taegis_sdk_python.services.alerts_history import AlertsHistoryService

log = logging.getLogger(__name__)


class TaegisSDKAlertsHistoryMutation:
    """Taegis Alerts_history Mutation operations."""

    def __init__(self, service: AlertsHistoryService):
        self.service = service
